Broke e.g. http://build.chromium.org/p/chromium.linux/builders/Linux%20Tests%20%28dbg%29%281%29/builds/24144/steps/browser_tests/logs/SuccessfulLoadUMA
NaClBrowserTestPnacl.SuccessfulLoadUMA: 
Right after fork
Right before base::type_profiler::Controller::Stop()
Right after base::type_profiler::Controller::Stop()
Right after signal/exception handler restoration.
Right after fd_shuffle push_backs.
Right after ShuffleFileDescriptors
Right after CloseSuperfluousFds
Right before execvp
HTTP server started on 127.0.0.1:58048...
sending server_data: {"host": "127.0.0.1", "port": 58048} (36 bytes)
Xlib:  extension "RANDR" missing on display ":9".
[17,713393920:04:05:40.227373] Native Client module will be loaded at base address 0x000029bb00000000
[17,731306368:04:05:43.588704] NaCl untrusted code called _exit(0x0)
[24356:24385:0321/210543:1859735606:INFO:nacl_process_host.cc(231)] NaCl process exited with status 0 (0x0)
[30,713393920:04:05:43.605721] Native Client module will be loaded at base address 0x00001a2c00000000
__PNACL_GENERATED:<SRPC stream>:function __unnamed_93: error: undefined reference to '__nacl_read_tp'
__PNACL_GENERATED:<SRPC stream>:function __unnamed_108: error: undefined reference to '__nacl_read_tp'
__PNACL_GENERATED:<SRPC stream>:function __unnamed_122: error: undefined reference to '__nacl_read_tp'
__PNACL_GENERATED:<SRPC stream>:function __unnamed_194: error: undefined reference to '__nacl_read_tp'
[24356:24356:0321/210544:1860321187:INFO:CONSOLE(0)] "NativeClient: NaCl module load failed: PnaclCoordinator: link failed.", source: http://127.0.0.1:58048/files/nacl_load_test.html (0)
[24356:24356:0321/210544:1860326955:INFO:nacl_browsertest_util.cc(75)] LOG Load error: NaCl module load failed: PnaclCoordinator: link failed.
[24356:24356:0321/210544:1860327667:INFO:nacl_browsertest_util.cc(75)] SHUTDOWN 1 test failed.
../../chrome/test/nacl/nacl_browsertest_util.cc:229: Failure
Value of: handler.test_passed()
Actual: false
Expected: true
Test failed.
../../chrome/test/base/uma_histogram_helper.cc:70: Failure
Value of: samples.GetCount(sample)
Actual: 0
Expected: expected_count
Which is: 1




Revert 189745 "NaCl: Update revision in DEPS, r11003 -> r11024"

> NaCl: Update revision in DEPS, r11003 -> r11024
> 
> This pulls in the following Native Client changes:
> 
> r11004: (shcherbina) Validator_ragel: get rid of redundant operand formats (they all are replaced with OPERAND_FORMAT_MEMORY).
> r11005: (shcherbina) Validator_ragel: get rid of unnecessary opcode_m and opcoder_r machines.
> r11006: (shcherbina) Validator_ragel: get rid of EXTRQ and INSERTQ exemption from decoder test.
> r11007: (shcherbina) Validator_ragel: move parse_instruction.rl out of unreviewed.
> r11008: (dschuff) Bump PNaCl TOOL_REVISIONS
> r11009: (jvoung) Disable -simplify-libcalls in pnacl-opt, unless --enable-simplify-libcalls.
> r11011: (dschuff) PNaCl: Update LLVM revision in pnacl/DEPS
> r11012: (shcherbina) Validator_ragel: cleanup now unnecessary comments in gen_dfa.py; introduce ALL_OPERAND_TYPES.
> r11013: (shcherbina) Validator_ragel: introduce X87_REGISTER_IN_OPCODE operand type in gen_dfa.py.
> r11014: (shcherbina) Validator_ragel: get rid of '/m', '/r' and '/s' 'opcodes' from instruction definitions.
> r11015: (sbc) Update expectations for pnacl_translator.opt.hw.arm runtime.
> r11017: (mcgrathr) toolchain_build: Update to new gmp, mpfr, mpc libraries
> r11019: (jvoung) Bump pnacl tools revision to 11011.
> r11020: (dschuff) Switch pnacl callingconv_ppapi test from using cc rewrite pass to biased bitcode
> r11021: (bsy) Prevent attempting to load the IRT twice
> r11022: (jvoung) Push archived pnacl frontend test rev higher, to 11011.
> r11023: (mseaborn) PNaCl: Enable the ExpandConstantExpr pass for ABI simplification
> r11024: (shcherbina) Validator_ragel: use lists of bytes instead of strings in DFA traversal.
> 
> BUG=none
> TEST=nacl_integration
> 
> Review URL: https://codereview.chromium.org/12983003

TBR=mseaborn@chromium.org
Review URL: https://codereview.chromium.org/12827014

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@189754 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: ad277c310d40972f8081f1264b0362147191c3da