Revert 53892 - Initial scriptable object implementation.
Broke ChromiumOS ARM build, reverting. Errors from log:
remoting/client/plugin/chromoting_scriptable_object.cc: In member function 'virtual bool remoting::ChromotingScriptableObject::HasProperty(const pp::Var&, pp::Var*)':
remoting/client/plugin/chromoting_scriptable_object.cc:48: error: NULL used in arithmetic
remoting/client/plugin/chromoting_scriptable_object.cc: In member function 'virtual bool remoting::ChromotingScriptableObject::HasMethod(const pp::Var&, pp::Var*)':
remoting/client/plugin/chromoting_scriptable_object.cc:63: error: NULL used in arithmetic

BUG=50248
TEST=write javascript to manually setup connection.

Review URL: http://codereview.chromium.org/3064009

TBR=ajwong@chromium.org
Review URL: http://codereview.chromium.org/3020038

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@53949 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 3d988d5dca3a77097a7176d7e753e43b1e6214b0