Revert 273652 "Host extensions"
gyp failure on Win:

Exception: Missing input files:

C:\b\build\slave\Win\build\src\remoting\host\extension.h

C:\b\build\slave\Win\build\src\remoting\host\extension_session.h


> Host extensions
> 
> This CL introduces HostExtension, an interface for classes that
> extend the host with non-core functionality.
> 
> Extensions are added to the ChromotingHost. They are used to compile
> the list of capabilities reported to the client, which can be used by
> the client to determine the availability of the extension.
> 
> When a client connects, a HostExtension has the opportunity to create
> an HostExtensionSession to hold client/extension state, and to handle
> extension messages from that client.
> 
> BUG=
> 
> Review URL: https://codereview.chromium.org/301453003

TBR=dcaiafa@chromium.org

Review URL: https://codereview.chromium.org/308743006

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@273674 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 057cf3c7b6c3d978436645f815337019769237eb