NaCl: Fix Python sys.path ordering in nacl_integration's browser tests
NaCl commit r12395 changed NaCl's Scons build so that it doesn't clear
out environment variables.  But this allows PYTHONPATH to leak into
browser_tester which causes it to import the wrong common.py module
from somewhere (I don't know where), giving this error:

Traceback (most recent call last):
  File "/Volumes/data/b/build/slave/mac/build/src/ppapi/native_client/tools/browser_tester/browser_tester.py", line 25, in <module>
    import memcheck_analyze
  File "/Volumes/data/b/build/slave/mac/build/src/ppapi/native_client/tools/browser_tester/../../../../tools/valgrind/memcheck_analyze.py", line 34, in <module>
    _BORING_CALLERS = common.BoringCallers(mangled=True, use_re_wildcards=True)
AttributeError: 'module' object has no attribute 'BoringCallers'

Fix this by using sys.path.insert(0, X), usually preferred over
sys.path.append(X).

(This was previously committed with a DEPS update in r235923, but that
got reverted.)

BUG=319585
TEST=nacl_integration

Review URL: https://codereview.chromium.org/76343002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@236016 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 604ce328ad19fafa691722bedade78332aca5a13