Revert 176243
Broke Mac Builder (dbg) compile:

../../chrome/browser/system_monitor/image_capture_device_manager_unittest.mm:121:3:error: instance method '-didDownloadFileerror:options:contextInfo:' not found (return type defaults to 'id') [-Werror,-Wobjc-method-access]
  [downloadDelegate didDownloadFile:file
  ^                 ~~~~~~~~~~~~~~~~~~~~
../../chrome/browser/system_monitor/image_capture_device_manager_unittest.mm:287:3:error: instance method '-deviceDidBecomeReadyWithCompleteContentCatalog:' not found (return type defaults to 'id') [-Werror,-Wobjc-method-access]
  [camera deviceDidBecomeReadyWithCompleteContentCatalog:nil];
  ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

> [Media Galleries] Add an ImageCaptureCore listener for Mac. (part 2)
> 
> This listener uses the ImageCapture API to watch for attach and detach
> events of PTP devices and other devices which can be read through the
> library. It forwards such notifications through the SystemMonitor.
> 
> Also provides an API for clients to access such devices directly and
> retrieve the media contents from them.
> 
> R=thestig@chromium.org,sail@chromium.org
> BUG=151681
> 
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=175471
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=175938
> 
> Review URL: https://chromiumcodereview.appspot.com/11442057

TBR=gbillock@chromium.org
Review URL: https://codereview.chromium.org/11862004

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@176251 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 302e0f230aa857d9e957ce29c14792776758afde