Revert 240602 "Use the caret bounds as a fallback when GetCompos..."
Broke RemoteInputMethodWinTest.OnCaretBoundsChanged

base\ime\remote_input_method_win_unittest.cc(423): error: Value of: mock_remote_delegate.composition_character_bounds()

> Use the caret bounds as a fallback when GetCompositionCharacterBounds is not available
> 
> This CL fixes a positional issue of IMEs' candidate window on PPAPI Flash running under Ash mode.
> 
> The root cause is that PPAPI does not support TextInputClient::GetCompositionCharacterBounds at all. We once worked around this in Issue 148903 but the Win/Ash backend lacked of this treatment.
> 
> BUG=328237
> TEST=manually done on Windows 8.1
> 
> Review URL: https://codereview.chromium.org/109323009

TBR=yukawa@chromium.org

Review URL: https://codereview.chromium.org/93933009

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@240627 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 260969bfeef6e5793a6143e77b69daac19d1088d