Revert 229632 "Set is_test_apk=1 for content_browsertests_apk."
This CL has caused content_browsertests to fail to
run on android_fyi_dbg with the following message:
(http://build.chromium.org/p/tryserver.chromium/builders/android_fyi_dbg_trigg...)

I  212s Main  [F00A]> am start -a android.intent.action.MAIN -S -W -n org.chromium.content_browsertests_apk/org.chromium.content_browsertests_apk.ContentBrowserTestsActivity
# 10/23/13 09:22:28: No response for adb -s 014E0FAC0500F00A shell 'am start -a android.intent.action.MAIN -S -W -n org.chromium.content_browsertests_apk/org.chromium.content_browsertests_apk.ContentBrowserTestsActivity', retrying
# 10/23/13 09:22:48: No response for adb -s 014E0FAC0500F00A shell 'am start -a android.intent.action.MAIN -S -W -n org.chromium.content_browsertests_apk/org.chromium.content_browsertests_apk.ContentBrowserTestsActivity', retrying
# 10/23/13 09:23:08: No response for adb -s 014E0FAC0500F00A shell 'am start -a android.intent.action.MAIN -S -W -n org.chromium.content_browsertests_apk/org.chromium.content_browsertests_apk.ContentBrowserTestsActivity', retrying
W  292s Main  Failed obtaining tests from 014E0FAC0500F00A with exception: 
Traceback (most recent call last):
  File "build/android/test_runner.py", line 776, in <module>
    sys.exit(main(sys.argv))
  File "build/android/test_runner.py", line 772, in main
    return command_option_parser.ParseAndExecute(option_parser)
  File "/b/build/slave/android/build/src/build/android/pylib/utils/command_option_parser.py", line 75, in ParseAndExecute
    return cmd.run_command_func(argv[1], options, args, option_parser)
  File "build/android/test_runner.py", line 692, in RunTestsCommand
    return _RunGTests(options, option_parser.error, devices)
  File "build/android/test_runner.py", line 498, in _RunGTests
    runner_factory, tests = gtest_setup.Setup(gtest_options, devices)
  File "/b/build/slave/android/build/src/build/android/pylib/gtest/setup.py", line 303, in Setup
    tests = _GetTestsFromDevice(TestRunnerFactory, devices)
  File "/b/build/slave/android/build/src/build/android/pylib/gtest/setup.py", line 216, in _GetTestsFromDevice
    raise Exception('No device available to get the list of tests.')
Exception: No device available to get the list of tests.

> Set is_test_apk=1 for content_browsertests_apk.
> 
> Without this set, you won't get the android_tools target
> built when building only content_browsertests_apk, which is needed
> in order to run the test on a device.
> 
> In WebRTC, I'm adding buildbots using that target for building and
> running content_browsertests in https://codereview.chromium.org/26738003/
> 
> I would like to avoid having to specify a separate target in
> android_all.gyp just to get this build running, and I think all targets
> should build their necessary dependencies.
> 
> TEST=local building of content_browsertests_apk + verifying the
> host_forwarder was built.
> BUG=305749
> 
> Review URL: https://codereview.chromium.org/27622005

TBR=kjellander@chromium.org

Review URL: https://codereview.chromium.org/38753003

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@230574 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: c8cddfec562bf2b317598c5847a3d23a68a050ac