Fix a crash in record_wpr when a tab crashes.
Stack trace:

Traceback (most recent call last):
  File "tools/perf/record_wpr", line 13, in <module>
    sys.exit(record_wpr.Main(benchmark_dir))
  File "/home/default/skia-repo/buildbot/third_party/chromium_trunk/tools/telemetry/telemetry/page/record_wpr.py", line 107, in Main
    '\n'.join(results.errors) + '\n'.join(results.failures))
TypeError: sequence item 0: expected string, tuple found

Looks like maybe introduced in: https://codereview.chromium.org/15231002

I am not sure this is the best solution, feedback will be appreciated.

Review URL: https://chromiumcodereview.appspot.com/15894009

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@203269 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 995d06482f2b3b2d29a969dd686e438f2fe534e9