Revert of Stop passing chrome.test.fail as ErrorCallback (https://codereview.chromium.org/258523004/)
Reason for revert:
Suspected for making OpenAudioFiles/FileManagerBrowserTest.Test/{0,1} flaky/racy since http://build.chromium.org/p/chromium.chromiumos/builders/Linux%20ChromiumOS%20Tests%20%28dbg%29%282%29/builds/10706

Errors like: 

[26400:26400:0426/004939:INFO:CONSOLE(0)] "[FAIL] undefined: API Test Error in undefined: Displayed data of 1st file is wrong.
Actual: Beautiful Song.ogg
Expected: Beautiful Song
...
    at chrome-extension://oobinhbdbiehknkpbpejbbpdbkdjmoco/open_audio_files.js:90:21", source: chrome-extension://oobinhbdbiehknkpbpejbbpdbkdjmoco/_generated_background_page.html (0)
[26400:26400:0426/004939:INFO:CONSOLE(0)] "[FAIL] undefined: chrome.test.failure

Original issue's description:
> Stop passing chrome.test.fail as ErrorCallback
> 
> chrome.test.fail cannot be used as ErrorCallback because it throws exception when the number of arguments doesn't match.
> This wrong use of chrome.test.fail makes the error output useless when something goes wrong.
> 
> BUG=None
> TEST=browser_tests
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=266271

TBR=hirono@chromium.org,hashimoto@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=None

Review URL: https://codereview.chromium.org/254943002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@266416 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 71a8ae673957596498c27f3688979e21e86ac76c