Revert 185178: Broke CrOS build:
chromeos-chrome-27.0.1425.0_alpha-r1: ui/base/x/events_x.cc: In function 'gfx::Point {anonymous}::CalibrateTouchCoordinates(const XIDeviceEvent*)':
chromeos-chrome-27.0.1425.0_alpha-r1: ui/base/x/events_x.cc:722:59: error: 'class gfx::Display' has no member named 'bounds_in_pixel'
http://build.chromium.org/p/chromium.chromiumos/builders/ChromiumOS%20%28daisy%29/builds/7530/steps/BuildTarget/logs/stdio

> Refactor DisplayInfo/Display
> 
> This is a first step to fix overscan issue and implement
> screen rotation.
> 
> * remove bounds_in_pixel from gfx::Display
> * promote DisplayInfo to separate class/file
> * All display information is now generated in display_change_observer_x11.cc.
>   almost no X11 depenency in display_manager.cc
>  (I'll move FindInternalDisplayID out from display_manager.cc once https://codereview.chromium.org/12217120/ is landed)
> 
>   This makes testing more consistent with real environment.
> 
> * Add DisplayManager::ClearCustomOverscanInsets so that
>   you can reset the insets to default value.
> * Removed obsolete AshTestBase::ChangeDisplayConfig
> 
> BUG=174721,119268
> TEST=covered by test
> 
> Review URL: https://chromiumcodereview.appspot.com/12218045

TBR=oshima@chromium.org
Review URL: https://codereview.chromium.org/12386017

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@185188 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 1ec0736284a1cc8c44610900f704b3e681c544b3