Revert 117968 - Rename is_hsts_host to fatal.
Per wtc: the old name was too specific, and became confusing because we now
also have certificate errors that users cannot override, but for reasons
other than (although still closely related to) HSTS.

Failures were:

http://chromegw.corp.google.com/i/chromium/builders/XP%20Tests%20%28dbg%29%286%29/builds/7935
http://chromegw.corp.google.com/i/chromium/builders/XP%20Tests%20%28dbg%29%282%29/builds/13488

(view as text)
WorkerFileSystemTest.FileWriterSyncTruncateExtend: 
[1132:3724:0117/155729:2434562:INFO:ui_layout_test.cc(57)] Assume LayoutTests in E:\b\build\slave\XP_Tests__dbg__6_\build\src\chrome\test\data\layout_tests\LayoutTests
[1132:3724:0117/155729:2434562:INFO:ui_layout_test.cc(143)] Assume LayoutTests in fast\filesystem
[1132:3724:0117/155730:2434765:INFO:ui_layout_test.cc(143)] Assume LayoutTests in fast\js
.\test\ui\ui_test.cc(720): error: Failed
Timeout reached in WaitUntilCookieNonEmpty
Google Test trace:
.\test\ui\ui_layout_test.cc(174): file-writer-sync-truncate-extend.html
.\test\ui\ui_layout_test.cc(254): error: Value of: inner_text.c_str()
  Actual: "[Worker] Test using FileWriterSync.truncate to extend a file.

On success, you will see a series of "PASS" messages, followed by "TEST COMPLETE".

Starting worker: ../resources/file-writer-sync-truncate-extend.js

"
Expected: expected_result_value.c_str()
Which is: "[Worker] Test using FileWriterSync.truncate to extend a file.

On success, you will see a series of "PASS" messages, followed by "TEST COMPLETE".

Starting worker: ../resources/file-writer-sync-truncate-extend.js
PASS [Worker] Truncate extension verified.
PASS successfullyParsed is true

TEST COMPLETE

"
Google Test trace:
.\test\ui\ui_layout_test.cc(174): file-writer-sync-truncate-extend.html


BUG=109941
Review URL: https://chromiumcodereview.appspot.com/9188019

TBR=palmer@chromium.org

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@118001 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: dfe3aad2dac8cd555e8f66085218a1c44e386fa4