Revert of Replace --ppapi-keep-alive-throttle command line switch with IPC parameter. (https://codereview.chromium.org/197693003/)
Reason for revert:
Broke building on http://build.chromium.org/p/chromium.memory/builders/Chromium%20OS%20%28x86%29%20ASan/builds/8599/steps/BuildPackages/logs/stdio

This bot builds with disable_nacl=1 for some reason (mentioned in the stdio above somewhere – not sure why this is), and thus chrome_browser doesn't depend on nacl_browser, leading to this linker error when building browser_tests:

chromeos-chrome-35.0.1889.0_alpha-r1: ../../../../../../../home/chrome-bot/chrome_root/src/chrome/browser/extensions/app_background_page_apitest.cc:134: error: undefined reference to 'nacl::NaClProcessHost::SetPpapiKeepAliveThrottleForTesting(unsigned int)'


(Maybe this change generally breaks building browser_tests with disable_nacl=1?)

Original issue's description:
> Replace --ppapi-keep-alive-throttle command line switch with IPC parameter.
> 
> Part of a broad effort to reduce the number of command line switches.
> 
> This is the second land of this change - correcting a static initializer issue.
> 
> BUG=350510
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=256961

TBR=dmichael@chromium.org,tsepez@chromium.org,mseaborn@chromium.org,scheib@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=350510

Review URL: https://codereview.chromium.org/199933002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@256993 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 34855e6c8666d51b92ef025a4f238e4c594c6d5e