Revert 205265 "payments dialog: remove edit links from Views UI"
Breaks Mac compile:
../../chrome/browser/ui/cocoa/autofill/autofill_section_container.mm:329:50: error: no member named 'editable' in 'autofill::SuggestionState'
  [suggestContainer_ setEditable:suggestionState.editable];
                                 ~~~~~~~~~~~~~~~ ^

> payments dialog: remove edit links from Views UI
> 
> BUG=245901
> R=aruslan@chromium.org, dbeam@chromium.org
> 
> Review URL: https://codereview.chromium.org/16521002

TBR=estade@chromium.org

Review URL: https://codereview.chromium.org/16751002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@205279 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 8f5f978d5b5b5473a04e065c02f33f4cb88407f4