Fix tautological compares in font_atlas.cc.
This fixes the following warnings from a recent version of Clang:

cc/font_atlas.cc:62:43: error: comparison of constant 128 with
expression of type 'char' is always true
[-Werror,-Wtautological-constant-out-of-range-compare]

cc/font_atlas.cc:45:39: error: comparison of constant 128 with
expression of type 'const char' is always true
[-Werror,-Wtautological-constant-out-of-range-compare]

The problem is that the char type is signed on this platform, and
therefore always < 128. The code really wants to work with the unsigned
values here.

BUG=163104


Review URL: https://chromiumcodereview.appspot.com/11416239

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@170041 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 2315d03ac792d2465dc1e89bdc7a2e69fdf93395