fix build after clang roll
../../chrome/browser/sync_file_system/drive_backend/sync_engine.cc:33:21:error:
field 'weak_ptr_factory_' is uninitialized when used here
[-Werror,-Wuninitialized]
      task_manager_(weak_ptr_factory_.GetWeakPtr()),
                    ^

This is wrong as WeakPtrFactory should be last, but let's fix the build for now
(and the code as-is is broken too, so it's not making things worse).

This was broken by https://codereview.chromium.org/26594002/

BUG=303818,290204
TBR=dmichael@chromium.org

Review URL: https://codereview.chromium.org/26775010

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@228322 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 900a800705913b5e06da7d7666e2ffd333e6235d