Revert 192420 "Move login switches to src/chromeos"
It seems to break compile on Google Chrome ChromeOS:

http://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20ChromeOS/builds/51573/steps/compile/logs/stdio

chrome/browser/ui/webui/options/browser_options_handler.cc: In member function 'void options::BrowserOptionsHandler::SetupMetricsReportingSettingVisibility()':
chrome/browser/ui/webui/options/browser_options_handler.cc:1422: error: 'kGuestSession' is not a member of 'switches'


> Move login switches to src/chromeos
> 
> We will need access to these switches in src/chromeos as we migrate
> login code there.
> 
> BUG=226495
> 
> Review URL: https://codereview.chromium.org/13532012

TBR=stevenjb@chromium.org
Review URL: https://codereview.chromium.org/13671003

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@192431 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: f1cb6fa1040cb4c558ccafed39949b3a2a39789e