Fix a lint issue with ActivityContentVideoViewClient.java.
Currently, the lint warns at:
Error: Field requires API level 16 (current min is 14):
    android.view.View#SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION [InlinedApi]
Error: Field requires API level 16 (current min is 14):
    android.view.View#SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN [InlinedApi]
Error: Field requires API level 16 (current min is 14):
    android.view.View#SYSTEM_UI_FLAG_FULLSCREEN [InlinedApi]

So we need to add @SuppressLint("InlinedApi") to suppress these lint errors.

BUG=327768

Review URL: https://codereview.chromium.org/305333002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@274273 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 8b3c7f0dd6fe844fbf6ba3ef97e085bb8dd4198b