Revert 134389 - Fix an incorrectly written policy test. It was using a hook incorrectly and checking for the wrong condition.
+++++++++++++++++++++++
REVERT NOTES

Broke test
http://build.chromium.org/p/chromium.pyauto/builders/Win7/builds/21229/steps/pyauto_functional_tests/logs/stdio

======================================================================
ERROR: policy.PolicyTest.testDefaultSearchProviderOptions: "Verify a default search is performed when using omnibox."
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\b\build\slave\Win7\build\src\chrome\test\functional\policy.py", line 533, in testDefaultSearchProviderOptions
    self.OmniboxAcceptInput()
  File "src\chrome\test\functional\..\pyautolib\pyauto.py", line 1184, in OmniboxAcceptInput
    self._GetResultFromJSONRequest(cmd_dict, windex=windex)
  File "src\chrome\test\functional\..\pyautolib\pyauto.py", line 1052, in _GetResultFromJSONRequest
    additional_info))
JSONInterfaceError: Automation call {'command': 'OmniboxAcceptInput'} received empty response.  Additional information:
No information available.
+++++++++++++++++++++++++

BUG=
TEST=functional/policy.py


Review URL: http://codereview.chromium.org/10256005

TBR=craigdh@chromium.org
Review URL: https://chromiumcodereview.appspot.com/10255022

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@134444 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: b3acaa3bdcfce0f2bb6a4ac480462d511e9d7526