NaCl: Fix link time error when DISABLE_NACL is set
This fixes breakage on the ARM buildbot, introduced by r54113.
nacl::Close() is not available when DISABLE_NACL is set.

The error was:
nacl_process_host.cc: error: undefined reference to 'nacl::Close(int)'

BUG=none
TEST=none (no trybot for the ARM build)

Review URL: http://codereview.chromium.org/3023025

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@54123 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 990b29ed176c85f5f48b913ca13fe79c1c0c2af9