Revert 263093 "roll skia DEPS to 14128"
Broke iOS Simulator (dbg):
http://build.chromium.org/p/chromium.mac/builders/iOS%20Simulator%20%28dbg%29/builds/15778

Ld /b/build/slave/iOS_Simulator__dbg_/build/src/xcodebuild/Debug-iphonesimulator/components_unittests.app/components_unittests normal i386
[...]
Undefined symbols for architecture i386:
  "SkSSE2ProcCoeffXfermode::SkSSE2ProcCoeffXfermode(SkReadBuffer&)", referenced from:
      SkSSE2ProcCoeffXfermode::CreateProc(SkReadBuffer&) in libskia_library.a(SkXfermode.o)
ld: symbol(s) not found for architecture i386

> roll skia DEPS to 14128
> 
> Chromium base revision: 262955 / 
> Old Skia revision: 14102 
> New Skia revision: 14128
> Control CL: https://codereview.chromium.org/233193002/
> 
> Bypassing commit queue trybots: 
> NOTRY=true
> 
> Review URL: https://codereview.chromium.org/232783004

TBR=bensong@google.com

Review URL: https://codereview.chromium.org/234103003

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@263112 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 7b69cb9b8bbef0c44a3b06ee6d3cb86ca4002d4f