Fix linux_aura clang build.
Fix the following chromium-style warning:
../../chrome/browser/ui/views/frame/desktop_browser_frame_aura.h:43:3: error: [chromium-style] Overriding method must have "virtual" keyword.

By adding the missing 'virtual' keyword.

TEST=build/gyp_chromium -Duse_aura=1, ninja -C out/Debug chrome should link.
TBR=sky@chromium.org


Review URL: https://chromiumcodereview.appspot.com/11316277

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@170531 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 59e440481c4b7a9eb4f8d2353cc3e0242dbb26b3