Disable FileWriterDelegateTest.WritesWithQuotaAndOffset, which has been flaky on Windows.
[ RUN      ] FileWriterDelegateTest.WritesWithQuotaAndOffset
..\webkit\fileapi\file_writer_delegate_unittest.cc(367): error: Value of: test_helper_.GetCachedOriginUsage()
  Actual: 45
Expected: ComputeCurrentOriginUsage()
Which is: 0
[  FAILED  ] FileWriterDelegateTest.WritesWithQuotaAndOffset (16 ms)

TBR=kinuko@chromium.org 
BUG=129264
TEST=NONE
Review URL: https://chromiumcodereview.appspot.com/10411084

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@138411 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 11c50f80822afbb9dfabadbd521fdb4e454ad1ca