Revert 196235 "Swap touch HUD when switching primary display"
Causes clang compile errors:
ash/touch/touch_observer_hud_unittest.cc:226:54:error: format specifies type 'long' but the argument has type 'int64' (aka 'long long') [-Werror,-Wformat]
    DisplayInfo info(id, base::StringPrintf("x-%ld", id), false);
                                               ~~~   ^~
                                               %lld

> Swap touch HUD when switching primary display
> 
> When a display is set as the primary display, its root window (and all
> its children, including the widget showing the touch HUD) is replaced
> with the old one's. But, the touch HUD widget is bound to display and
> should not be swapped between the two displays. So, after swapping the
> root windows, touch HUDs are swapped back to their own display.
> 
> BUG=172237
> 
> Review URL: https://chromiumcodereview.appspot.com/13460017

TBR=mohsen@chromium.org

Review URL: https://codereview.chromium.org/14481002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@196237 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 76cbe549234460026d3454d1de0784e26747a486