Protect header that requires SSE2 on gcc4.4 and remove unused header.
This fixes a compile error on the new 32-bit Lucid buildbots:

In file included from net/tools/flip_server/balsa_headers.cc:7:
/usr/lib/gcc/i486-linux-gnu/4.4.3/include/emmintrin.h:32:3: error: #error "SSE2 instruction set not enabled"
In file included from net/tools/flip_server/balsa_frame.cc:8:
/usr/lib/gcc/i486-linux-gnu/4.4.3/include/emmintrin.h:32:3: error: #error "SSE2 instruction set not enabled"

BUG=
TEST=Lucid builbot compiles

Review URL: http://codereview.chromium.org/6677116

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@80292 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 175b1ce2327e4cbcad0851fa03b02021b2fe50c3