Adding a missing header.
The official build was broken by r175584:
> host\desktop_process_main.cc(114): error C2039: 'InitializeCrashReporting' : is not a member of 'remoting'
> host\desktop_process_main.cc(114): error C3861: 'InitializeCrashReporting': identifier not found

Only the official builders were affected since remoting::InitializeCrashReporting() call is guarded by "#ifdef OFFICIAL_BUILD".

BUG=134694

Review URL: https://codereview.chromium.org/11827024

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@175865 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: d2a866e1338ca8d0765fafb7aa72d368313c5d1d