When NEON disabled, always build ARM memset routines.
Fixes:
...SkUtils_opts_arm.cpp:36:error: undefined reference to 'arm_memset16'
...SkUtils_opts_arm.cpp:53:error: undefined reference to 'arm_memset32'

BUG=155921,277433
TEST=Fixes missing memset routine during linking.
R=mtklein@google.com, reed@google.com

Review URL: https://codereview.chromium.org/391793002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@283220 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: f7bc14484d1272bb3cf0d62d65ae6f0a171eaed3