Fix Mac Breakpad glue compilation error:
breakpad_mac.mm:137: error: 'parsed_command_line' was not declared in this scope

since r31143

BUG=none
TEST=Breakpad-enabled build should, um, build
Review URL: http://codereview.chromium.org/374011

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@31246 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 2ff8afa71ab7098f8ab2d72a33cd9a21a6c7a4e1