Revert 250830 "Exclude notification strings for builds that dont..."
> Exclude notification strings for builds that dont use it.
> 
> BUG=326023
> 
> Review URL: https://codereview.chromium.org/160113002

Broke win64 sync tests, e.g. output:

c:\b\build\slave\cr-win-rel-x64\build\src\chrome\browser\sync\test\integration\sync_test.cc(707): error: Value of: UTF16ToASCII(browser()->tab_strip_model()->GetActiveWebContents()-> GetTitle())
  Actual: ""
Expected: "Notifications enabled"

TBR=aurimas@chromium.org

Review URL: https://codereview.chromium.org/163713002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@251003 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 837cf5b4af15a3b4ec086843794d3421f4f6bcee