Revert 240630 "roll gyp 1806:1814"
Broke Win Builder (dbg) runhooks:

  File "C:\b\build\slave\cr-win-dbg\build\src\tools\gyp\pylib\gyp\generator\msvs.py", line 223, in _ConvertSourcesToFilterHierarchy
      folders = collections.OrderedDict()
  AttributeError: 'module' object has no attribute 'OrderedDict'

> roll gyp 1806:1814
> 
> r1807 win msvs: make ordering match .gyp order
> r1808 Fix gyptest-app for Xcode 5.0.2
> r1809 Fix gyptest-xcode-gcc.py when using Xcode 5.0.2
> r1810 Fix gyptest-sdkroot when oldest SDK is >= 10.8
> r1811 Fix gyptest-xcode-env-order for Xcode 5.0.0
> r1812 win msvs: Make ordering of sources in subdir
> r1813 win ninja: Refactor manifest generate and embed to be 1-pass
> r1814 win ninja: default to embedding manifest to match msvs
> 
> TBR=thakis@chromium.org
> BUG=324863,276953,326030
> 
> Review URL: https://codereview.chromium.org/111203005

TBR=scottmg@chromium.org

Review URL: https://codereview.chromium.org/99213005

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@240641 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 885ebc6c2f00b50e2e806e196bc41d55f1a15b45