Revert 131593
Speculatively reverting due to gyp update error on official bots:

KeyError: 'src/breakpad/breakpad.gyp:dump_syms#target while trying to load target src/remoting/remoting.gyp:remoting_linux_symbols#target'

This is the only patch in the regression range that touches breakpad.gyp.

---
Upstream Android native crash handling changes.

This is actulaly the second time.

Revert "Revert 131404 - Upstream native crash handling changes for Android."

This reverts commit 421df96aab6267e963ddff16c9f738aa903a2cba.

Conflicts:

	chrome/browser/chrome_browser_main.cc

BUG=
TEST=


Review URL: http://codereview.chromium.org/9967017

TBR=carlosvaldivia@google.com
Review URL: https://chromiumcodereview.appspot.com/10037013

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@131600 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 9603fa7f011a3a6fddd9df0f02b92aa1bd279024