Revert "Web MIDI: enable important logs in release build"
This reverts commit 5be5a60207940b3a329ca94934713571b4741d53 [formerly 73113403b7d0fa04308689ebc79e765f65a3efad].

This is causing chromeos bot failures:

snippet:
chromeos-chrome-34.0.1842.0_alpha-r1:
../../../../../../../home/chrome-bot/chrome_root/src/content/browser/browser_main_loop.cc:475:
error: undefined reference to 'media::MidiManager::Create()'
chromeos-chrome-34.0.1842.0_alpha-r1: collect2: error: ld returned 1 exit status
chromeos-chrome-34.0.1842.0_alpha-r1: ninja: build stopped: subcommand failed.

link to full output:
http://build.chromium.org/p/chromium.chromiumos/builders/ChromiumOS%20%28amd64%29/builds/14268/steps/BuildPackages/logs/stdio

TBR=toyoshim@chromium.org
BUG=None

Review URL: https://codereview.chromium.org/168523002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@251567 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 52a486a8db7720ea0a55f9993750819adabeed1c