Mark flaky.
[ RUN      ] ChromeFrameTestWithWebServer.FullTabModeIE_WindowClose
.\test\test_with_web_server.cc(214): error: Value of: server_mock_.posted_result()
  Actual: ""
Expected: result
Which is: "OK"
[  FAILED  ] ChromeFrameTestWithWebServer.FullTabModeIE_WindowClose (45217 ms)


BUG=111074
TEST=marked flaky


Review URL: http://codereview.chromium.org/9235013

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@118822 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 726c98651c4b2be8242f89937d1c4c6dd56f77b9