Revert of GestureRecognizerTest tests both Aura and Unified Gesture Detectors. (https://codereview.chromium.org/258633005/)
Reason for revert:
Breaks compile on

http://build.chromium.org/p/chromium.linux/builders/Linux%20Builder%20%28dbg%29%2832%29/builds/23390

../../ui/aura/gestures/gesture_recognizer_unittest.cc: In constructor 'aura::test::{anonymous}::GestureEventConsumeDelegate::GestureEventConsumeDelegate()':
../../ui/aura/gestures/gesture_recognizer_unittest.cc:354:17: error: 'aura::test::{anonymous}::GestureEventConsumeDelegate::wait_until_event_' will be initialized after [-Werror=reorder]
../../ui/aura/gestures/gesture_recognizer_unittest.cc:352:7: error:   'int aura::test::{anonymous}::GestureEventConsumeDelegate::flags_' [-Werror=reorder]
../../ui/aura/gestures/gesture_recognizer_unittest.cc:70:3: error:   when initialized here [-Werror=reorder]

Original issue's description:
> GestureRecognizerTest tests both Aura and Unified Gesture Detectors.
> 
> This is in preparation of landing the unified GR
> (see https://codereview.chromium.org/251543003/).
> 
> There are some cases where behavior differs in minor ways.
> 
> This is sometimes dealt with by increasing the test's margin of error
> (for instance, slop handling is slightly different, so we now
> exceed the slop more thoroughly).
> 
> This is sometimes dealt with by ignoring the test if the test is
> run with the unified GR.
> 
> BUG=332418
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=266440

TBR=sadrul@chromium.org,tdresser@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=332418

Review URL: https://codereview.chromium.org/254963003

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@266443 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 65c1762fc82a799e974dd26af31363f79519fa27