Revert 218584 "Support a new remote IPC for for GetTerminationSt..."
Broke the ChromiumOS (amd64) bot:
chromeos-chrome-31.0.1607.0_alpha-r1: chrome/nacl/nacl_helper_linux.cc: In function 'int main(int, char**)':
chromeos-chrome-31.0.1607.0_alpha-r1: chrome/nacl/nacl_helper_linux.cc:369:33: error: narrowing conversion of 'sysconf(84)' from 'long int' to 'int' inside { } is ill-formed in C++11 [-Werror=narrowing]
http://build.chromium.org/p/chromium.chromiumos/builders/ChromiumOS%20%28amd64%29/builds/10667

> Support a new remote IPC for for GetTerminationStatus.
> 
> This does three things:
> 
> 1. Clean-up a lot of the code in the Linux NaCl loader.
> 2. Create a new IPC to the NaCl loader "Zygote" for the
> main Zygote to query the termination status of processes.
> 3. Clean-up some code in the Zygote and fix "process tracking".
> 
> zygote_linux.cc:
>  * Split GetTerminationStatus() out from HandleGetTerminationStatus().
>  * Handle the case where we need to perform a remote IPC for GetTerminationStatus()
>  * Use the new GetTerminationStatus() to support the remote case for HandleReapRequest().
>  * Replace real_pids_to_sandbox_pids mapping with process_info_map_.
>     * Update shortcut case in ForkWithRealPid() to fill this out.
>     * Update GetTerminationStatus() to remove existing entries.
> 
> zygote_fork_delegate_linux.h:
>  * Create a new GetTerminationStatus() interface.
> 
> nacl_helper_linux.cc:
>  * Split HandleZygoteRequest() out from main().
>  * Split ChildNaClLoaderInit() to handle the child side of a fork().
>  * Handle a new IPC in HandleGetTerminationStatusRequest().
> 
> nacl_fork_delegate_linux.cc:
>  * Implement the new GetTerminationStatus() interface.
>  * Use Pickle for IPCs, make IPCs easier to write with SendIPCRequestAndReadReply().
> 
> BUG=133453
> R=mseaborn@chromium.org, piman@chromium.org
> 
> Review URL: https://codereview.chromium.org/23020010

TBR=jln@chromium.org

Review URL: https://codereview.chromium.org/22886011

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@218602 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 297a9dbd5be7f6fa01b25b8eeeb48da70f7494e4