Revert 192563 "Fix DownloadExtensionTest_OnDeterminingFilename_I..."
This test failed on Vista Tests bot:

http://build.chromium.org/p/chromium.win/builders/Vista%20Tests%20(2)/builds/33887/steps/browser_tests/logs/DownloadExtensionTest_OnDeterminingFilename_InterruptedResume

DownloadExtensionTest.DownloadExtensionTest_OnDeterminingFilename_InterruptedResume: 
[0405/091818:ERROR:gl_surface_egl.cc(98)] eglInitialize failed with error
UNKNOWN
[0405/091818:ERROR:gl_surface_win.cc(54)] GLSurfaceEGL::InitializeOneOff failed.
HTTP server started on 127.0.0.1:51868...
sending server_data: {"host": "127.0.0.1", "port": 51868} (36 bytes)
browser\extensions\api\downloads\downloads_api_unittest.cc(3222): error: Value
of: item->GetState()
Actual: 0
Expected: DownloadItem::INTERRUPTED
Which is: 3
browser\extensions\api\downloads\downloads_api_unittest.cc(3223): error: Value
of: item->IsInterrupted()
Actual: false
Expected: true

> Fix DownloadExtensionTest_OnDeterminingFilename_InterruptedResume
> 
> Review URL: https://codereview.chromium.org/12422012

TBR=benjhayden@chromium.org
Review URL: https://codereview.chromium.org/13598016

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@192579 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 41b335044a58cf95759078a19a22f075783b93d3