Revert 222957 "Refactors TestSystemTrayDelegate into DefaultSyst..."
It broke Aura windows builder

FAILED: ninja -t msvc -e environment.x86 -- C:\b\build\goma\gomacc.exe "c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\cl.exe" /nologo /showIncludes /FC @obj\ash\test\ash_test_support.test_system_tray_delegate.obj.rsp /c ..\..\ash\test\test_system_tray_delegate.cc /Foobj\ash\test\ash_test_support.test_system_tray_delegate.obj /Fdobj\ash\ash_test_support.pdb 
c:\b\build\slave\win_aura_builder\build\src\ash\test\test_system_tray_delegate.cc(24) : error C2220: warning treated as error - no 'object' file generated
c:\b\build\slave\win_aura_builder\build\src\ash\test\test_system_tray_delegate.cc(24) : warning C4273: 'ash::test::TestSystemTrayDelegate::TestSystemTrayDelegate' : inconsistent dll linkage
        c:\b\build\slave\win_aura_builder\build\src\ash\test\test_system_tray_delegate.h(15) : see previous definition of '{ctor}'
c:\b\build\slave\win_aura_builder\build\src\ash\test\test_system_tray_delegate.cc(28) : warning C4273: 'ash::test::TestSystemTrayDelegate::~TestSystemTrayDelegate' : inconsistent dll linkage
        c:\b\build\slave\win_aura_builder\build\src\ash\test\test_system_tray_delegate.h(16) : see previous definition of '{dtor}'
c:\b\build\slave\win_aura_builder\build\src\ash\test\test_system_tray_delegate.cc(33) : warning C4273: 'ash::test::TestSystemTrayDelegate::SetInitialLoginStatus' : inconsistent dll linkage
        c:\b\build\slave\win_aura_builder\build\src\ash\test\test_system_tray_delegate.h(23) : see previous definition of 'SetInitialLoginStatus'
c:\b\build\slave\win_aura_builder\build\src\ash\test\test_system_tray_delegate.cc(37) : warning C4273: 'ash::test::TestSystemTrayDelegate::SetLoginStatus' : inconsistent dll linkage
        c:\b\build\slave\win_aura_builder\build\src\ash\test\test_system_tray_delegate.h(30) : see previous definition of 'SetLoginStatus'
c:\b\build\slave\win_aura_builder\build\src\ash\test\test_system_tray_delegate.cc(42) : warning C4273: 'ash::test::TestSystemTrayDelegate::GetUserLoginStatus' : inconsistent dll linkage
        c:\b\build\slave\win_aura_builder\build\src\ash\test\test_system_tray_delegate.h(37) : see previous definition of 'GetUserLoginStatus'
c:\b\build\slave\win_aura_builder\build\src\ash\test\test_system_tray_delegate.cc(61) : warning C4273: 'ash::test::TestSystemTrayDelegate::ShouldShowDisplayNotification' : inconsistent dll linkage
        c:\b\build\slave\win_aura_builder\build\src\ash\test\test_system_tray_delegate.h(38) : see previous definition of 'ShouldShowDisplayNotification'
c:\b\build\slave\win_aura_builder\build\src\ash\test\test_system_tray_delegate.cc(65) : warning C4273: 'ash::test::TestSystemTrayDelegate::ShutDown' : inconsistent dll linkage
        c:\b\build\slave\win_aura_builder\build\src\ash\test\test_system_tray_delegate.h(39) : see previous definition of 'ShutDown'
c:\b\build\slave\win_aura_builder\build\src\ash\test\test_system_tray_delegate.cc(69) : warning C4273: 'ash::test::TestSystemTrayDelegate::SignOut' : inconsistent dll linkage
        c:\b\build\slave\win_aura_builder\build\src\ash\test\test_system_tray_delegate.h(40) : see previous definition of 'SignOut'
ninja: build stopped: subcommand failed.


> Refactors TestSystemTrayDelegate into DefaultSystemTrayDelegate
> 
> DefaultSystemTrayDelegate is the no-op implementation and
> TestSystemTrayDelegate contains the test related bits.
> 
> This also fixes a crash in the windows side as
> TestSystemTrayDelegate::Shutdown() quits the message loop, which is
> the wrong thing to do.
> 
> BUG=159693 284358
> TEST=none
> R=oshima@chromium.org
> 
> Review URL: https://chromiumcodereview.appspot.com/23465018

TBR=sky@chromium.org

Review URL: https://codereview.chromium.org/23650004

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@222973 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 39594f64142380e8ed8e06e10deb1396d0fa52dc