Revert 277111 "Roll ICU to icu52"
It breaks a bunch of bots with a compile time error

../out/Release/gen/tc_pnacl_newlib/lib/libicuuc_nacl.a: error: undefined reference to 'icudt52_dat'
For example: http://build.chromium.org/p/chromium.memory/builders/Linux%20ASan%20LSan%20Builder/builds/7531



> Roll ICU to icu52
> 
> The ICU update does the following among other things:
>   - Update EUC-JP (no more JIS X 212 round-trip coverage) per WHATWG 
>     encoding spec.
>   - Add CP866
>   - Add far better/more extensive support for plural, format, etc
>   - Numerous locale data update
>   - Khmer/Lao line/word-breaking support
>   - More compact Chinese/Japanese dictionary (now a part of the upstream
>     instead of our local patch)
>   - Better plural support that we plan to use right away.
> 
> - Update icu/BUILD.gn : file list update, new defines, etc.
> - Update tests
>   a. icu_string_conversions_unittests : drop iscii (nobody uses it) and
>      remove JIS X 212 code points from the round-trip test
>   b. l10n_util_unittests: Display names for zh-*.
>   c. ThaiSnippet's expected result. (due to a Unicode grapheme definition change).
>   d. Update Expected results in file_manager_browsertest/test_util.js
>      (see http://crbug.com/383930)
> - Update SpellcheckerWordIterator 
>   a. Add U+0027 back to MidNumLet
>   b. Add Lao and Khmer scripts to the list of scripts requiring dictionary-based
>      word-breaking.
> - l10n_util : alias 'tl' to 'fil' (Tagalog to Filipino) 
> - Update IdentityInternalsSingleTokenWebUITest.verifyGetters (DateTimeFormat-Full
>   has 'at' before time, which is not handled by Date.parse()
> - update license.py because we don't have a separate Chinese/Japanese
>   dictionary any more. It's now a part of ICU
> 
> BUG=132145,277023,136148,360433,364072
> TEST=base_unittests:*ICU*, net_unittests:*IDN*, ui_unittests:*Lang*,
>      browser_tests (encoding related, Iden*verifyGet*), 
>      unit_tests:Ext*L10*, unit_tests:*Lang*, component_tests:*Snipp*,
>      layout tests (encoding, date/calendar, line breaking, and others),
>      build 'base_i18n_nacl', GN build bots.
> 
> Review URL: https://codereview.chromium.org/265613002

TBR=jshin@chromium.org

Review URL: https://codereview.chromium.org/336793004

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@277117 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: d7285fc3158696fedf1c1e337c0680b71669e438