Revert 271477 "Skia roll 14765:14785"
This broke the Google Chrome Mac build.

http://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20Mac/builds/18028

[3268/23724 | 168.537] RULE Generating binding from ../core/fileapi/FileReader.idl
FAILED: /Volumes/data/b/build/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/third_party/skia/src/gpu/effects/skia_library.GrDashingEffect.o.d -DV8_DEPRECATION_WARNINGS -DBLINK_SCALE_FILTERS_AT_RECORD_TIME -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORE=0 -DGOOGLE_CHROME_BUILD -DCR_CLANG_REVISION=206824 -DENABLE_RLZ -DUSE_LIBJPEG_TURBO=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DUSE_PROPRIETARY_CODECS -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DENABLE_HIDPI=1 -DDISCARDABLE_MEMORY_ALWAYS_SUPPORTED_NATIVELY -DSYSTEM_NATIVELY_SIGNALS_MEMORY_PRESSURE -DENABLE_EGLIMAGE=1 -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGIN_INSTALLATION=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DENABLE_FULL_PRINTING=1 -DENABLE_PRINTING=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_MANAGED_USERS=1 -DENABLE_SERVICE_DISCOVERY=1 -DSK_ENABLE_INST_COUNT=0 -DSK_SUPPORT_GPU=1 '-DGR_GL_CUSTOM_SETUP_HEADER="GrGLConfig_chrome.h"' -DSK_ENABLE_LEGACY_API_ALIASING=1 -DSK_ATTR_DEPRECATED=SK_NOTHING_ARG1 -DGR_GL_IGNORE_ES3_MSAA=0 -DSK_WILL_NEVER_DRAW_PERSPECTIVE_TEXT -DSK_SUPPORT_LEGACY_PUBLICEFFECTCONSTRUCTORS=1 -DSK_SUPPORT_LEGACY_GETTOPDEVICE -DSK_SUPPORT_LEGACY_N32_NAME -DSK_SUPPORT_LEGACY_BUILDMIPMAP -DSK_SUPPORT_LEGACY_GETTOTALCLIP -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=0 -DSK_DISABLE_OFFSETIMAGEFILTER_OPTIMIZATION -DSK_DISABLE_PIXELREF_LOCKCOUNT_BALANCE_CHECK -DIGNORE_ROT_AA_RECT_OPT -DSK_IGNORE_BLURRED_RRECT_OPT -DSK_IGNORE_QUAD_RR_CORNERS_OPT -DSK_GDI_ALWAYS_USE_TEXTMETRICS_FOR_FONT_METRICS '-DSK_DEFAULT_FONT_CACHE_LIMIT=(20*1024*1024)' -DSK_USE_DISCARDABLE_SCALEDIMAGECACHE -DSK_BUILD_FOR_MAC -DSK_GAMMA_SRGB -DSK_GAMMA_CONTRAST=0.0 -DSK_HIGH_QUALITY_IS_LANCZOS -DSK_USE_POSIX_THREADS -DSK_DEFERRED_CANVAS_USES_FACTORIES=1 -DSK_IGNORE_UNDERLINE_POSITION_FIX -DNDEBUG -DOFFICIAL_BUILD -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/images -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pdf -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/record -I../../third_party/skia/include/utils -I../../third_party/skia/src/core -I../../third_party/skia/src/opts -I../../third_party/skia/src/image -I../../third_party/skia/src/ports -I../../third_party/skia/src/sfnt -I../../third_party/skia/src/utils -I../../third_party/skia/src/lazy -I../.. -I../../skia/config -I../../third_party/skia/include/gpu -I../../third_party/skia/src/gpu -I../../third_party/skia/include/utils/mac -I../../third_party/zlib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.6.sdk -O3 -gdwarf-2 -fvisibility=hidden -Wnewline-eof -mmacosx-version-min=10.6 -arch i386 -Wendif-labels -Wno-unused-parameter -Wno-missing-field-initializers -Wheader-hygiene -Wno-c++11-narrowing -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wno-deprecated-register -Wno-absolute-value -Wno-selector-type-mismatch -std=gnu++11 -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -fno-threadsafe-statics -Xclang -load -Xclang /Volumes/data/b/build/slave/google-chrome-rel-mac/build/src/tools/clang/scripts/../../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.dylib -Xclang -add-plugin -Xclang find-bad-constructs -fcolor-diagnostics -fno-strict-aliasing  -c ../../third_party/skia/src/gpu/effects/GrDashingEffect.cpp -o obj/third_party/skia/src/gpu/effects/skia_library.GrDashingEffect.o
../../third_party/skia/src/gpu/effects/GrDashingEffect.cpp:142:5: error: use of undeclared identifier 'SkPaint2GrPaintShader'
    SkPaint2GrPaintShader(dev, paint, true, &grPaint);
    ^

> Skia roll 14765:14785
> 
> https://code.google.com/p/skia/source/list?num=19&start=14785
> TBR=
> BUG=
> 
> Review URL: https://codereview.chromium.org/290713005

TBR=robertphillips@google.com

Review URL: https://codereview.chromium.org/293803002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@271488 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 1ef2656d0c0f1cdb3366013d9adebb39cc197093