Fix bug caught by clang's -Wlogical-not-parentheses
../../chromeos/process_proxy/process_output_watcher_unittest.cc:49:9: error: logical not is only applied to the left hand side of this comparison [-Werror,-Wlogical-not-parentheses]
    if (!type == PROCESS_OUTPUT_TYPE_OUT)
        ^     ~~
../../chromeos/process_proxy/process_output_watcher_unittest.cc:49:9: note: add parentheses after the '!' to evaluate the comparison first
    if (!type == PROCESS_OUTPUT_TYPE_OUT)
        ^
         (                              )
../../chromeos/process_proxy/process_output_watcher_unittest.cc:49:9: note: add parentheses around left hand side expression to silence this warning
    if (!type == PROCESS_OUTPUT_TYPE_OUT)
        ^
        (    )

Since PROCESS_OUTPUT_TYPE_OUT evaluates to 0, this doesn't change behavior.

BUG=262248
R=tbarzic@chromium.org

Review URL: https://codereview.chromium.org/19517008

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@212910 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: e2524b02ec1e8505542acd495242a3def7d85b3f