Revert of Cast:Add resolution settings to receiver app (https://codereview.chromium.org/203223003/)
Reason for revert:
Breaks compilation on Linux x64 bot:

http://build.chromium.org/p/chromium/builders/Linux%20x64/builds/62808

../../media/cast/test/receiver.cc:99:60:error: invalid conversion from 'int' to 'const char*' [-fpermissive]
...

Original issue's description:
> Cast:Add resolution settings to receiver app
> 
> 
> Add an option for the user the set the resolution in run-time,
> plus some clean up.
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=257948

TBR=pwestin@chromium.org,mikhal@chromium.org
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/203683006

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@257956 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 2f0b8d865ee3087b789b7138198a9e9d6eb543e1