Initialize self._wsout.
If websocket_server.py is called with --server stop, it will call
Stop without calling Start, so it claims as follows:
  AttributeError: 'PyWebSocket' object has no attribute '_wsout'

Review URL: http://codereview.chromium.org/545023

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@35998 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 712b963929cf9eae60f475a35e21ed180d1bdbf7