Fix invalid array access in OnRobustJPEGDecodeImage().
This doesn't seem to be a problem for release builds, but in debug builds the invalid array access causes STL errors:

    error: attempt to subscript container with out-of-bounds index 0, but
    container only holds 0 elements.

BUG=401161

Review URL: https://codereview.chromium.org/446853002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@287884 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 2bb5a856f69e91ddfc03642f760fc435d646e451