Revert 269445 "Auth work to support new auth protocol"
Compile failure on linux.

FAILED: /b/build/goma/gomacc c++ -MMD -MF obj/chrome/browser/extensions/api/cast_channel/browser_extensions.cast_auth_util_nss.o.d -DV8_DEPRECATION_WARNINGS -DBLINK_SCALE_FILTERS_AT_RECORD_TIME -D_FILE_OFFSET_BITS=64 -DCHROMIUM_BUILD -DCOMPONENT_BUILD -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DUSE_X11=1 -DUSE_CLIPBOARD_AURAX11=1 -DENABLE_ONE_CLICK_SIGNIN -DUSE_XI2_MT=2 -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DUSE_UDEV -DENABLE_EGLIMAGE=1 -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGIN_INSTALLATION=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DENABLE_FULL_PRINTING=1 -DENABLE_PRINTING=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_MANAGED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DFULL_SAFE_BROWSING -DGL_GLEXT_PROTOTYPES -DMOJO_USE_SYSTEM_IMPL -DGTEST_HAS_POSIX_RE=0 -DLIBPEERCONNECTION_LIB=1 -DPROTOBUF_USE_DLLS -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DSKIA_DLL -DGR_GL_IGNORE_ES3_MSAA=0 -DSK_ENABLE_INST_COUNT=0 -DSK_SUPPORT_GPU=1 '-DGR_GL_CUSTOM_SETUP_HEADER="GrGLConfig_chrome.h"' -DSK_ENABLE_LEGACY_API_ALIASING=1 -DSK_ATTR_DEPRECATED=SK_NOTHING_ARG1 -DSK_WILL_NEVER_DRAW_PERSPECTIVE_TEXT -DSK_SUPPORT_LEGACY_PUBLICEFFECTCONSTRUCTORS=1 -DSK_SUPPORT_LEGACY_GETTOPDEVICE -DSK_SUPPORT_LEGACY_N32_NAME -DSK_SUPPORT_LEGACY_BLURMASKFILTER_STYLE -DSK_SUPPORT_LEGACY_GETTOTALCLIP -DSK_USE_POSIX_THREADS -DSK_DEFERRED_CANVAS_USES_FACTORIES=1 -DFEATURE_ENABLE_SSL -DFEATURE_ENABLE_VOICEMAIL -DEXPAT_RELATIVE_PATH -DGTEST_RELATIVE_PATH -DNO_MAIN_THREAD_WRAPPING -DNO_SOUND_SYSTEM -DLINUX -DPOSIX -DU_USING_ICU_NAMESPACE=0 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_LINUX -DUSE_NSS=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -D_DEBUG -I../.. -Iobj/chrome/browser_extensions.gen -Iobj/chrome/browser_extensions.gen/chrome -I../../third_party/khronos -I../../gpu -I../../skia/config -I../../third_party/WebKit/Source -Igen/protoc_out -I../../third_party/protobuf -I../../third_party/protobuf/src -Igen/chrome -Igen -I../../third_party/re2 -Igen/components/strings -I../../third_party/WebKit -I../../net/third_party/nss/ssl -Igen/extensions/strings -I../../third_party/skia/src/core -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/pdf -I../../third_party/skia/include/gpu -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../skia/ext -I../../third_party/libjingle/overrides -I../../third_party/libjingle/source -I../../testing/gtest/include -I../../third_party -I../../third_party/webrtc -I../../third_party/cacheinvalidation/overrides -I../../third_party/cacheinvalidation/src -I../../third_party/icu/source/i18n -I../../third_party/icu/source/common -I../../third_party/leveldatabase/src/include -I../../third_party/leveldatabase/src -I../../third_party/leveldatabase -Igen/ui/app_locale_settings -Igen/ui/ui_strings -Igen/ui/ui_resources -Igen/webkit -Igen/ui/keyboard -Igen/policy -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-exceptions -fno-strict-aliasing -Wall -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -pthread -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/include/nss -I/usr/include/nspr -I/usr/include/dbus-1.0 -I/usr/lib/i386-linux-gnu/dbus-1.0/include -msse2 -mfpmath=sse -mmmx -m32 -O0 -g -funwind-tables -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -Wsign-compare  -c ../../chrome/browser/extensions/api/cast_channel/cast_auth_util_nss.cc -o obj/chrome/browser/extensions/api/cast_channel/browser_extensions.cast_auth_util_nss.o
../../chrome/browser/extensions/api/cast_channel/cast_auth_util_nss.cc: In function 'bool {anonymous}::VerifyCredentials(const extensions::api::cast_channel::AuthResponse&, const string&)':
../../chrome/browser/extensions/api/cast_channel/cast_auth_util_nss.cc:263:60: error: invalid conversion from 'const SECItem* {aka const SECItemStr*}' to 'SECItem* {aka SECItemStr*}' [-fpermissive]
/usr/include/nss/keyhi.h:215:1: error:   initializing argument 1 of 'SECKEYPublicKey* SECKEY_ImportDERPublicKey(SECItem*, CK_KEY_TYPE)' [-fpermissive]
ninja: build stopped: subcommand failed.

> Auth work to support new auth protocol
> 
> BUG=345759
> 
> Review URL: https://codereview.chromium.org/254083007

TBR=munjal@chromium.org

Review URL: https://codereview.chromium.org/273123003

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@269454 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 2f75bdfdc60cafdfee88ad8fa377d7414d82e6fa