Revert 240548 "Enable platform echo cancellation through the Aud..."
Causing compile failure on Chromium OS bots:

chromeos-chrome-33.0.1738.0_alpha-r1: media/audio/cras/audio_manager_cras.cc:126:10: error: no matching constructor
chromeos-chrome-33.0.1738.0_alpha-r1:       for initialization of 'media::AudioParameters'
chromeos-chrome-33.0.1738.0_alpha-r1:   return AudioParameters(

Logs:
http://build.chromium.org/p/chromium.chromiumos/builders/ChromiumOS%20%28x86%29/builds/18585
http://build.chromium.org/p/chromium.chromiumos/builders/ChromiumOS%20%28amd64%29/builds/12929
http://build.chromium.org/p/chromium.chromiumos/builders/ChromiumOS%20%28daisy%29/builds/14979
http://build.chromium.org/p/chromium.memory/builders/Chromium%20OS%20%28amd64%29%20ASAN/builds/8140
http://build.chromium.org/p/chromium.memory/builders/Chromium%20OS%20%28x86%29%20ASAN/builds/7509

> Enable platform echo cancellation through the AudioRecord path.
> 
> Add a platform effects mask member to AudioParameters. This allows the
> availability of platform effects (currently AEC) to be plumbed up to
> MediaStreamDependencyFactory, where they can be reconciled with the
> media constraints to determine if the effects should be enabled. When
> this is the case, the constraints will be modified to disable the
> corresponding software effect in PeerConnection.
> 
> The availability is controlled by a whitelist of device models in
> AudioManagerAndroid, which for AEC, currently consists of Nexus 5 and
> Nexus 7.
> 
> AudioManagerAndroid will use the AudioRecord path iff the platform
> AEC is enabled.
> 
> TESTED=Using apprtc on a N5 and N7 (whitelisted):
> - The AudioRecord input path is used.
> - The platform AEC is enabled and the software AEC (in PeerConnection)
> is disabled.
> - Calls have good echo cancellation quality.
> 
> Using apprtc with ?audio=googEchoCancellation=false on a N5 and N7:
> - The OpenSLES input path is used.
> - Both the platform and software AEC are disabled.
> 
> Using apprtc on Nexus 4 (non-whitelisted):
> - The OpenSLES input path is used.
> - The platform AEC is disabled and the software AEC is enabled.
> 
> Using apprtc on Galaxy S2 (running ICS):
> - The OpenSLES input path is used.
> 
> audio_android_unittest.cc passes on N5, N7 and Galaxy S2
> 
> TBR=jschuh
> 
> Review URL: https://codereview.chromium.org/99033003

TBR=ajm@chromium.org

Review URL: https://codereview.chromium.org/110303003

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@240592 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 7ec092e25d8a596a6cf5f0366bd5aff13121902d