Revert 88095.
This broke the clang bot thusly:

/b/build/slave/Mac_Clang__dbg_/build/src/chrome/browser/accessibility/browser_accessibility_cocoa.mm:218:66:error: '&&' within '||' [-Werror,-Wlogical-op-parentheses]
    if (browserAccessibilityRole != WebAccessibility::ROLE_GROUP &&
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/b/build/slave/Mac_Clang__dbg_/build/src/chrome/browser/accessibility/browser_accessibility_cocoa.mm:218:66: note: place parentheses around the '&&' expression to silence this warning
    if (browserAccessibilityRole != WebAccessibility::ROLE_GROUP &&
                                                                 ^

It looks like this might be a real bug.

88095 - Add accessibility support for tab, tablist, and tabpanel to Mac.
    
    Use the WebUI settings page as an end to end example of the attributes.  The
    BUG=83253
    TEST=manually test VoiceOver on settings page.



Add accessibility support for tab, tablist, and tabpanel to Mac.

Use the WebUI settings page as an end to end example of the attributes.  The navbar uses tab and tablist.  The navbar also now correctly handles left and right arrow keys to move the focus from tab to tab.
BUG=83253
TEST=manually test VoiceOver on settings page.


Review URL: http://codereview.chromium.org/7058037

TBR=dtseng@chromium.org
Review URL: http://codereview.chromium.org/7131002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@88099 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: a3520ba91af9c8d30fb1e6d589b54a190ec1a9df