Revert 178354
Broke Linux Chromium OS ASAN:
http://build.chromium.org/p/chromium.memory/builders/Linux%20Chromium%20OS%20ASAN%20Builder/builds/4509/steps/compile/logs/stdio

In file included from ../../chromeos/attestation/attestation_flow_unittest.cc:7:
../../chromeos/attestation/mock_attestation_flow.h:23:3:error: [chromium-style] Overriding method must have "virtual" keyword.
  void SendEnrollRequest(const std::string& request,
    ^
    ../../chromeos/attestation/mock_attestation_flow.h:24:56:error: [chromium-style] virtual methods with non-empty bodies shouldn't be declared inline.
                             const DataCallback& callback) {


> Implemented attestation message flow for Chrome OS.
>     
> Chrome OS has an attestation service which can interact with a Privacy CA in order to generate an attestation certificate.  The AttestationFlow class coordinates this interaction.
> 
> BUG=chromium-os:37806
> TEST=unit
> 
> 
> Review URL: https://chromiumcodereview.appspot.com/11932004

TBR=dkrahn@google.com
Review URL: https://codereview.chromium.org/12042056

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@178358 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 3fd9722d3be919596658747fd26335879d64d55d