It broke win aura bot
[ RUN      ] WindowTest.TransferCaptureTouchEvents
.\window_unittest.cc(700): error: Value of: d1.gesture_event_count()
  Actual: 2
Expected: 1
.\window_unittest.cc(710): error: Value of: d2.gesture_event_count()
  Actual: 2
Expected: 1
[  FAILED  ] WindowTest.TransferCaptureTouchEvents (0 ms)

Revert 140967 - Fix TAP_DOWN gesture event:
1. GESTURE_TAP_DOWN should be sent only on the first TOUCH_PRESSED.
2. New gesture GESTURE_BEGIN shuold be sent on all TOUCH_PRESSED.
3. Rename GESTURE_TAP_UP to GESTURE_END.

BUG=131007
TEST=manual


Review URL: https://chromiumcodereview.appspot.com/10533029

TBR=varunjain@chromium.org
Review URL: https://chromiumcodereview.appspot.com/10539041

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@140972 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 735dce06ed30b61b49de10642f45566ec612a5d5