Revert of Componentize SigninManager. (https://codereview.chromium.org/218713002/)
Reason for revert:
Believed to have caused http://build.chromium.org/p/chromium.memory/builders/Linux%20ASan%2BLSan%20Builder/builds/2113 to fail.

../../chrome/browser/profiles/gaia_info_update_service.h:14:10: fatal error: 'chrome/browser/signin/signin_manager.h' file not found
#include "chrome/browser/signin/signin_manager.h"

Original issue's description:
> Componentize SigninManager.
> 
> This CL does the following:
> 
> - Componentizes SigninIdAccountHelper, on which SigninManager depends
> - Abstracts SigninManager's (embedder-level) calculation of whether to merge
>   signin credentials into the cookie jar via SigninClient
> - Eliminates the |profile| argument of SigninManagerBase::Initialize() now that
>   SigninManager no longer needs it
> - Componentizes SigninManager
> 
> BUG=334209,333998
> TBR=thakis
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=260636

TBR=droger@chromium.org,thakis@chromium.org,blundell@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=334209,333998

Review URL: https://codereview.chromium.org/218613008

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@260641 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 8a5af39fb3304a6f4cee881026000fbee8f78f89