NaCl: browser_tester: Don't call server_close() because it causes EBADF
This change should stop the HTTP server thread from outputting the
following backtrace, which clutters the logs (and is sometimes
interleaved with other output):

Traceback (most recent call last):
  File ".../tools/browser_tester/browser_tester.py", line 247, in Serve
    server.handle_request()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/SocketServer.py", line 262, in handle_request
    fd_sets = select.select([self], [], [], timeout)
select.error: (9, 'Bad file descriptor')

BUG=none
TEST=checked log output on Mac OS X

Review URL: https://codereview.chromium.org/11819005

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@175634 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 3bfcde88e99f693369f5f758f1ef7be6d75e5c4d