[gcc 4.8] Explicitly initialize net_error in ProxyRetryInfo to fix build failure
gcc 4.8 reports build failure as net_error is not explicitly initialized. The error
thrown is as below -

net/proxy/proxy_retry_info.h: In member function
‘virtual void net::{anonymous}::ProxyListTest_DeprioritizeBadProxies_Test::TestBody()’:
net/proxy/proxy_retry_info.h:15:8: error: ‘proxy_retry_info.net::ProxyRetryInfo::net_error’
is used uninitialized in this function [-Werror=uninitialized]

R=kundaji@chromium.org, rsleevi@chromium.org

Review URL: https://codereview.chromium.org/485603002

Cr-Commit-Position: refs/heads/master@{#290239}
git-svn-id: svn://svn.chromium.org/chrome/trunk/src@290239 0039d316-1c4b-4281-b951-d872f2087c98
(cherry picked from commit eaedac69488879cc1b4a1b8f1d73a069bba268a3 [formerly fc687ad3b2a0181afd01a226dce9d295c04495a1])

BUG=

Review URL: https://codereview.chromium.org/573293002

Cr-Commit-Position: refs/branch-heads/2125@{#376}
Cr-Branched-From: a07ab98aac4efe79cac896c518413e1413d4de46 [formerly b68026d94bda36dd106a3d91a098719f952a9477]-refs/heads/master@{#290040}

Former-commit-id: 3899adf4feed16f111c038d8a3a3a4ca60c3475c