drive: Fix a build failure due to 64-bit constants
On some configurations, the build was broken with errors like:

  chrome/browser/chromeos/drive/search_metadata_unittest.cc:133: error: integer constant is too large for ‘long’ type

LL suffix was needed for 64-bit constants.

BUG=none
TEST=none

Review URL: https://codereview.chromium.org/12223019

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@180852 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 93efeeef513d49ab50a5585590693622eb8d6d01