[Telemetry] Better error messages.
New output:
ERROR:root:http://googlewebmastercentral.blogspot.com/:
Traceback (most recent call last):
  File "/work/chromium/src/tools/perf/../telemetry/telemetry/page/page_runner.py", line 440, in _RunPage
    test.Run(finder_options, page, page_state.tab, results)
  File "/work/chromium/src/tools/perf/../telemetry/telemetry/page/page_test.py", line 208, in Run
    self._RunCompoundAction(page, tab, compound_action)
  File "/work/chromium/src/tools/perf/../telemetry/telemetry/page/page_test.py", line 229, in _RunCompoundAction
    action.RunAction(page, tab, prev_action)
  File "/work/chromium/src/tools/perf/../telemetry/telemetry/page/actions/wait.py", line 33, in RunAction
    tab.PerformActionAndWaitForNavigate(action_to_perform, self.timeout)
  File "/work/chromium/src/tools/perf/../telemetry/telemetry/core/tab.py", line 83, in PerformActionAndWaitForNavigate
    action_function, timeout)
  File "/work/chromium/src/tools/perf/../telemetry/telemetry/core/backends/chrome/inspector_backend.py", line 167, in PerformActionAndWaitForNavigate
    self._page.PerformActionAndWaitForNavigate(action_function, timeout)
  File "/work/chromium/src/tools/perf/../telemetry/telemetry/core/backends/chrome/inspector_page.py", line 72, in PerformActionAndWaitForNavigate
    'Error=%s' % (timeout, sys.exc_info()[1]))
TimeoutException: Timed out while waiting 60s for navigation. Error=Received a socket error in the browser connection and the tab still exists, assuming it timed out. Timeout=0s Elapsed=0s Error=[Errno 35] Resource temporarily unavailable

Pages: []
RESULT telemetry_page_measurement_results: num_failed= 0 count
RESULT telemetry_page_measurement_results: num_errored= 1 count
ERROR:root:Errored pages:
Blogger

BUG=

Review URL: https://codereview.chromium.org/66933002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@234157 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 3e4c212814ff6f96db6b8fffda749e7b8856e911