Drop unused variable in rlz_value_store_chromeos.cc.
../../rlz/chromeos/lib/rlz_value_store_chromeos.cc:24:12: error: unused variable 'kProductChrome' [-Werror,-Wunused-const-variable]
const char kProductChrome[] = "chrome";
           ^
../../rlz/chromeos/lib/rlz_value_store_chromeos.cc:25:12: error: unused variable 'kProductOther' [-Werror,-Wunused-const-variable]
const char kProductOther[] = "other";
           ^
2 errors generated.

BUG=307668
TEST=none
R=thakis@chromium.org

Review URL: https://codereview.chromium.org/33373002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@229874 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 661efff48213dd3c79fc47d1f77df32124e49c5a