Revert 206289 "Removed patch to GCC-style assembly in third_part..."
Caused compile failure on Linux.

FAILED: gcc -MMD -MF obj/third_party/lzma_sdk/lzma_sdk.CpuArch.o.d -D_FILE_OFFSET_BITS=64 -DUSE_LINUX_BREAKPAD -DCHROMIUM_BUILD -DCOMPONENT_BUILD -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DUSE_NSS=1 -DUSE_X11=1 -DENABLE_ONE_CLICK_SIGNIN -DGTK_DISABLE_SINGLE_INCLUDES=1 -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_INPUT_SPEECH -DENABLE_NOTIFICATIONS -DENABLE_GPU=1 -DENABLE_EGLIMAGE=1 -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGIN_INSTALLATION=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_BACKGROUND=1 -DENABLE_AUTOMATION=1 -DENABLE_GOOGLE_NOW=1 -DENABLE_LANGUAGE_DETECTION=1 -DENABLE_PRINTING=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_MANAGED_USERS=1 -D_7ZIP_ST -D_LZMA_PROB32 -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -D_DEBUG -I../../third_party/lzma_sdk -fstack-protector --param=ssp-buffer-size=4 -pthread -fno-exceptions -fno-strict-aliasing -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wno-format -Wno-unused-result -m32 -mmmx -march=pentium4 -msse2 -mfpmath=sse -O0 -g   -c ../../third_party/lzma_sdk/CpuArch.c -o obj/third_party/lzma_sdk/lzma_sdk.CpuArch.o
../../third_party/lzma_sdk/CpuArch.c: In function 'MyCPUID':
../../third_party/lzma_sdk/CpuArch.c:75:3:error: inconsistent operand constraints in an 'asm'
ninja: build stopped: subcommand failed.


> Removed patch to GCC-style assembly in third_party/lzma_sdk.
> 
> Previously, this code caused a segmentation fault under certain compilers using optimization; in particular the high 32 bits of EBX are zeroed as a result of the mov instruction. However, if the compiler is using EBX to store a 64-bit address (which proved to be the case for Courgette), this results in a segmentation fault.
> 
> The following fixes were also considered and verified as working:
> `push $ebx` at the start of the modified assembly section and `pop $ebx` at the end.
> Add "ebx" to the clobber list of the instruction to prevent the compiler from depending upon it not being clobbered.
> 
> However, I can't seem to verify that the build breaks on Linux x86 without this change; so I don't see why we need this patch. Therefore, I've simply removed it.
> 
> BUG=248385
> TBR=bashi@chromium.org
> 
> Review URL: https://chromiumcodereview.appspot.com/16402015

TBR=waffles@chromium.org

Review URL: https://codereview.chromium.org/16869006

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@206297 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 234aab27f9922c8ae5512abe74875ca5f5469d79