Fix dupe line causing Linux official builder error.
Linux official builders are failing with:
test_expectations.py:364 ERROR Line:642 More specific entry on line 642
overrides line 20 svg/css/composite-shadow-text.svg

This updates the fix in r81732 which removed the dupe for Windows, but
by leaving the line without the platform, caused Linux to have a dupe
because of the svg/css/composite-shadow-text.svg line in
test_expectations_chrome.txt.

BUG=
TEST=Linux official builders run webkit_tests again.

Review URL: http://codereview.chromium.org/6879048

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@82324 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: e87b7125f9a8add5a47167166883a7cb01aa542d