Revert 123372 - Adds deps file for content/browser/accessibility/
DumpAccessibilityTreeTest.PlatformTreeDifferenceTest fails:
..\content\browser\accessibility\dump_accessibility_tree_browsertest.cc(106): error: Value of: actual_contents8
  Actual: "|ROLE_SYSTEM_DOCUMENT||IA2_STATE_HORIZONTAL|IA2_STATE_OPAQUE\n|IA2_ROLE_SECTION||IA2_STATE_HORIZONTAL|IA2_STATE_OPAQUE\n"
Expected: expected_contents
Which is: "|ROLE_SYSTEM_DOCUMENT||IA2_STATE_OPAQUE|IA2_STATE_VERTICAL\n|IA2_ROLE_SECTION||IA2_STATE_HORIZONTAL|IA2_STATE_OPAQUE\n"


Revert "Revert 122617 - Adds dump accessibility tree support in Windows."

This reverts commit 3f2f1c29061e018c0d9b4b4205d45e4607812672 [formerly ca8de581137b34eb04ca8b68186f143d4bea98e8].

BUG=
TEST=


Review URL: http://codereview.chromium.org/9429026

TBR=dtseng@chromium.org
Review URL: https://chromiumcodereview.appspot.com/9454033

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@123390 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: bc95a82163a28b9bf5b17685321a9bf8d6b55113