Revert 234877 "Update V8 to version 3.23.3.1."
Breaks SunSpider benchmark.

INFO:root:Running file://sunspider-1.0/driver.html

Traceback (most recent call last):
  <module> at tools/perf/run_benchmark:23
    sys.exit(test_runner.Main())
  Main at tools/telemetry/telemetry/test_runner.py:303
    return command.Run(options, args)
  Run at tools/telemetry/telemetry/test_runner.py:211
    return min(255, self._test().Run(copy.copy(options)))
  Run at tools/telemetry/telemetry/test.py:53
    results = page_runner.Run(test, ps, expectations, options)
  Run at tools/telemetry/telemetry/page/page_runner.py:330
    possible_browser, results, state)
  _PrepareAndRunPage at tools/telemetry/telemetry/page/page_runner.py:224
    results_for_current_run, finder_options)
  _RunPage at tools/telemetry/telemetry/page/page_runner.py:440
    test.Run(finder_options, page, page_state.tab, results)
  Run at tools/telemetry/telemetry/page/page_test.py:218
    self._test_method(page, tab, results)
  _RunTest at tools/telemetry/telemetry/page/page_measurement.py:54
    self.MeasurePage(page, tab, results)
  MeasurePage at tools/perf/benchmarks/sunspider.py:31
    total += value

Locals:
  _              : <telemetry.page.page.Page object at 0x101b306d0>
  js_get_results : 'JSON.stringify(output);'
  js_results     : [{u'math-spectral-norm': 2, u'bitops-3bit-bits-in-byte': 2, u ... u'bitops-bits-in-byte': 3, u'math-cordic': 3, u'3d-cube': 10}] (truncated)
  key            : u'3d-morph'
  r              : defaultdict(<type 'list'>, {u'math-spectral-norm': [2], u'3d- ...  u'bitops-3bit-bits-in-byte': [2], u'date-format-xparb': [7]}) (truncated)
  result         : {u'math-spectral-norm': 2, u'bitops-3bit-bits-in-byte': 2, u' ...  u'bitops-bits-in-byte': 3, u'math-cordic': 3, u'3d-cube': 10} (truncated)
  results        : <telemetry.page.buildbot_page_measurement_results.BuildbotPageMeasurementResults run=1 errors=0 failures=0>
  tab            : <telemetry.core.tab.Tab object at 0x101b4fc50>
  total          : 11
  totals         : []
  value          : u'NaN'

TypeError: unsupported operand type(s) for +=: 'int' and 'unicode'

> Update V8 to version 3.23.3.1.
> 
> TBR=jkummerow@chromium.org
> BUG=
> 
> Review URL: https://codereview.chromium.org/71483002

TBR=machenbach@chromium.org

Review URL: https://codereview.chromium.org/72103003

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@234945 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 5d52fa8364ede83e5279804795cd134995a2c014