Revert 115075 - NaCl: Update revision in DEPS, r7388 -> r7479
sbox_integration_test failure:

UnloadDllTest.UnloadAviCapDllNoPatching: 
.\src\unload_dll_test.cc(70): error: Value of: runner.RunTest(L"UseOneDLL L avicap32.dll")
  Actual: -441384956
Expected: SBOX_TEST_FAILED
Which is: -441384955

http://build.chromium.org/p/chromium/builders/Win7%20Tests%20%28dbg%29%283%29/builds/1351/steps/sbox_integration_tests/logs/stdio

This pulls in the following Native Client changes:

r7389: (dschuff) Some additional torture test failures with O3 not caught before
r7390: (krasin) Enable run_strto{,u}ll_test for x86-64. They were recently fixed.
r7391: (mseaborn) Re-enable multiple-sandboxes test on Windows
r7392: (pdox) Scons: Remove unused IrtIsBroken() function.
r7393: (jvoung) Clean out use_pnacl_irt from run.py now that bitcode=1 doesn't affect the IRT build.
r7394: (pasko) Add a quick-n-dirty nacl64-gdb attacher.
r7395: (robertm) Disable nacl_semaphore_test test when run under Qemu/arm because of flakiness.
r7396: (robertm) llvm-mc compatibility fix for nacl_text_pad_test.S
r7397: (noelallen) Bump Chrome 113806
r7399: (noelallen) Disable sel_universal tests broken by Chrome.
r7400: (jvoung) Pass arch argument along to pre-req checker in the all()
r7401: (mcgrathr) Remove unused next_outgoing_request_id member from struct NaClSrpcChannel
r7402: (pdox) Augment initfini test by adding 3 function pointers to each array. This will catch bugs in which preinit/init/fini_array elements are skipped due to pointer alignment/size issues.
r7403: (noelallen) Add ability to run test_hello_world_nexe for GLIBC
r7404: (pdox) Make elf_constants.h #includable without NACL_BUILD_ARCH/SUBARCH defined
r7405: (pdox) Tidy: Make NACL_x86/arm #defines more robust against NACL_BUILD_ARCH not being defined
r7406: (pdox) Revert 7405, due to broken gyp build.
r7407: (pdox) Merge with LLVM up to r146310.
r7408: (pdox) Add -Wno-array-bounds to SConstruct for PNaCl GlibC build.
r7409: (halyavin) Implement exception handling for stand-alone sel_ldr on Win32.
r7410: (jvoung) Roll toolchain DEPs.
r7412: (krasin) Add test for wcstoll.c which is currently broken for glibc.
r7413: (krasin) Revert 7412 - Add test for wcstoll.c which is currently broken for glibc.
r7414: (mcgrathr) Factor nameservice lookup out of manifest lookup code in IRT
r7415: (noelallen) Newlib buildbots RED due to dependency on glibc toolchain.
r7416: (krasin) Add test for wcstoll.c which is currently broken for glibc.
r7417: (mcgrathr) Filter -fstack-protector out of cflags for nacl_helper_bootstrap
r7418: (ncbray) Fix a indenting bug in build/chromebinaries.py.
r7419: (noelallen) Trivial fix to prevent recompile of toolchain .S files.
r7420: (mcgrathr) Update chrome_rev in DEPS
r7422: (mcgrathr) Add IRT interface for random number generator
r7423: (mcgrathr) Update glibc revision to daf2032
r7424: (krasin) Update llvm rev to caa4d07e5a3f. This bring in: revert local mod in arm mc.
r7425: (mcgrathr) Add a test that pthread_cleanup_push doesn't clobber nearby stack
r7426: (krasin) Revert 7424 - Update llvm rev to caa4d07e5a3f. This bring in: revert local mod in arm mc.
r7427: (pdox) Merge with LLVM up to r146520.
r7428: (pdox) Roll toolchain DEPS and commit test changes for CL:
r7430: (pdox) Whitespace change to trigger rebuild.
r7431: (mseaborn) Remove unused #define NACL_NO_INLINE
r7432: (pdox) Merge with LLVM up to r146552.
r7433: (dschuff) First step in refactoring.
r7434: (mcgrathr) Don't expect RNG to produce two different values for subsequent byte reads
r7435: (mcgrathr) Update glibc revision to 3c8d1f2
r7436: (kschimpf) Add pre/post conditions for unit testing of the validator for LEA instruction.
r7437: (mseaborn) Mac crash reporting: Add interface for distinguishing trusted/untrusted crashes
r7438: (mcgrathr) Bump toolchain DEPS, enable no-longer-broken tests
r7440: (bsy) NaCl-side changes for stdout/err redirection to postmessage.
r7441: (dschuff) Update bot name for pnacl toolchain tests, should cause bot to run
r7442: (dschuff) Add PNACL_BUILDBOT to tester env
r7443: (sehr) Add reverse channel support to sel_universal.  This will allow emulation of
r7444: (pdox) Add bias (architecture-specific defines, __x86_64__) to pthread_cleanup_test (for PNaCl GlibC build).
r7445: (pdox) Use the PNaCl-built crtbegin.o/crtend.o/crti.bc for GlibC build.
r7446: (sehr) Enable LD manifest name service change.
r7447: (jvoung) Rev bump for "Remove unnecessary localmod for a aeabi_atexit":
r7448: (mseaborn) Add missing 'extern "C"' to NaClMachThreadIsInUntrusted()
r7449: (noelallen) Fix glibc for windows.
r7450: (sehr) Remove spurious comments.
r7451: (mseaborn) Fix Mac crash filter to work before the sandbox has been initialised
r7452: (sehr) A little extra debug information.
r7453: (sehr) Remove now-irrelevant sections from the manifests in tests.
r7454: (dschuff) Modify toolchain_tester.py to run toolchain torture tests in parallel, based on the --concurrency argument.
r7455: (sehr) Get reverse channel interface changes in toolchain.
r7457: (bradchen) Revert "Modify toolchain_tester.py to run toolchain torture tests in parallel...."
r7458: (mseaborn) Make NACL_x86/arm #defines more robust against NACL_BUILD_ARCH not being defined
r7459: (pdox) Merge with LLVM up to r146722.
r7460: (sehr) Expose fix for double free in linker to toolchain build.
r7461: (mcgrathr) Add platform to standard buildbot step names in toolchain bot case
r7462: (jvoung) Limit pnacl IRT shim generation to only the public and dev APIs, so that
r7463: (garianov) Make NaCl gettimeofday() return time with ~10 microsecond resolution, on Windows. Take two.
r7464: (dschuff) Parallel torture tests, take 2
r7465: (bradchen) Chromium deps roll in NaCl
r7467: (pdox) Switch to using pnacl_abi.bc as a stub for libgcc_eh for GlibC shared/dynamic.
r7468: (dschuff) Re-enable llvm testsuite for x86
r7469: (jvoung) Roll toolchain deps to pull in sehr's ld fix.
r7471: (jvoung) Make unpacked pnacl support extension visible to browser tests.  This will remove the support files from the user's manifest and stop pulling from the user's server.
r7472: (pdox) pthread.h: Match posix definitions of pthread_cond_init and pthread_mutex_init.
r7473: (jvoung) Include one more gcc torture test.
r7474: (jvoung) Disable glibc copying in crx gen for some platforms.
r7475: (mseaborn) Relax NaClCreateMainThread()'s argc constraint in order to simplify tests
r7476: (pdox) Disable glibc copying in crx gen for x86-32 also. Tarball is currently only generated for linux X86-64.
r7477: (mseaborn) Partly fix untrusted-code Gyp build's tracking of dependencies on header files
r7478: (noelallen) Disalbe GLIBC by default, disable_glibc==0 required to enable.
r7479: (sehr) Get changes removing obsolete SRPC code.

BUG=none
TEST=nacl_integration


Review URL: http://codereview.chromium.org/8974015

TBR=mseaborn@chromium.org
Review URL: http://codereview.chromium.org/9004007

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@115081 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: c37878131bb73533d0e0164ccae8ecfd01631e41