Revert 251206 "Fixes crashes wrt to the maximize button when:"
> Fixes crashes wrt to the maximize button when:
> - A user hovers the minimize button with the mouse then taps the snap left / snap right button
> - When the MaximizeBubbleFrameState computed by GetMaximizeBubbleFrameState() changes while the maximize button help bubble is visible due to the work area bounds changing (See comment #6 in bug)
> 
> BUG=342867
> TEST=FrameMaximizeButtonTest.MaximizeBubbleMouseHoverAndTouch
> 
> Review URL: https://codereview.chromium.org/160493004

Reverting as broke compile on windows:

[2431/3743] CXX
obj\chrome\browser\extensions\api\cast_channel\browser_extensions.cast_auth_util_nss.obj
FAILED: ninja -t msvc -e environment.x64 -- C:\b\build\goma\gomacc.exe
"C:\Program Files (x86)\Microsoft Visual Studio
11.0\VC\bin\amd64\cl.exe" /nologo /showIncludes /FC
@obj\ash\wm\caption_buttons\ash.maximize_bubble_controller.obj.rsp /c
..\..\ash\wm\caption_buttons\maximize_bubble_controller.cc
/Foobj\ash\wm\caption_buttons\ash.maximize_bubble_controller.obj
/Fdobj\ash\ash.cc.pdb 
c:\b\build\slave\cr-win-rel-x64\build\src\ash\wm\caption_buttons\frame_maximize_button.h(73)
:error C3668: 'ash::FrameMaximizeButton::OnWindowShowTypeChanged' :
method with override specifier 'override' did not override any base
class methods
FAILED: ninja -t msvc -e environment.x64 -- C:\b\build\goma\gomacc.exe
"C:\Program Files (x86)\Microsoft Visual Studio
11.0\VC\bin\amd64\cl.exe" /nologo /showIncludes /FC
@obj\ash\wm\ash.custom_frame_view_ash.obj.rsp /c
..\..\ash\wm\custom_frame_view_ash.cc
/Foobj\ash\wm\ash.custom_frame_view_ash.obj /Fdobj\ash\ash.cc.pdb 
c:\b\build\slave\cr-win-rel-x64\build\src\ash\wm\caption_buttons\frame_maximize_button.h(73)
:error C3668: 'ash::FrameMaximizeButton::OnWindowShowTypeChanged' :
method with override specifier 'override' did not override any base
class methods
FAILED: ninja -t msvc -e environment.x64 -- C:\b\build\goma\gomacc.exe
"C:\Program Files (x86)\Microsoft Visual Studio
11.0\VC\bin\amd64\cl.exe" /nologo /showIncludes /FC
@obj\ash\wm\caption_buttons\ash.frame_caption_button_container_view.obj.rsp
/c ..\..\ash\wm\caption_buttons\frame_caption_button_container_view.cc
/Foobj\ash\wm\caption_buttons\ash.frame_caption_button_container_view.obj
/Fdobj\ash\ash.cc.pdb 
c:\b\build\slave\cr-win-rel-x64\build\src\ash\wm\caption_buttons\frame_maximize_button.h(73)
:error C3668: 'ash::FrameMaximizeButton::OnWindowShowTypeChanged' :
method with override specifier 'override' did not override any base
class methods
FAILED: ninja -t msvc -e environment.x64 -- C:\b\build\goma\gomacc.exe
"C:\Program Files (x86)\Microsoft Visual Studio
11.0\VC\bin\amd64\cl.exe" /nologo /showIncludes /FC
@obj\ash\wm\caption_buttons\ash.maximize_bubble_controller_bubble.obj.rsp
/c ..\..\ash\wm\caption_buttons\maximize_bubble_controller_bubble.cc
/Foobj\ash\wm\caption_buttons\ash.maximize_bubble_controller_bubble.obj
/Fdobj\ash\ash.cc.pdb 
c:\b\build\slave\cr-win-rel-x64\build\src\ash\wm\caption_buttons\frame_maximize_button.h(73)
:error C3668: 'ash::FrameMaximizeButton::OnWindowShowTypeChanged' :
method with override specifier 'override' did not override any base
class methods
FAILED: ninja -t msvc -e environment.x64 -- C:\b\build\goma\gomacc.exe
"C:\Program Files (x86)\Microsoft Visual Studio
11.0\VC\bin\amd64\cl.exe" /nologo /showIncludes /FC
@obj\ash\wm\caption_buttons\ash.frame_maximize_button.obj.rsp /c
..\..\ash\wm\caption_buttons\frame_maximize_button.cc
/Foobj\ash\wm\caption_buttons\ash.frame_maximize_button.obj
/Fdobj\ash\ash.cc.pdb 
c:\b\build\slave\cr-win-rel-x64\build\src\ash\wm\caption_buttons\frame_maximize_button.h(73)
:error C3668: 'ash::FrameMaximizeButton::OnWindowShowTypeChanged' :
method with override specifier 'override' did not override any base
class methods
ninja: build stopped: subcommand failed.

from: http://build.chromium.org/p/chromium.win/builders/Win%20x64%20Builder/builds/14916/steps/compile/logs/stdio#error1

TBR=pkotwicz@chromium.org

Review URL: https://codereview.chromium.org/165283003

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@251217 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 0e17bb74283205bc01f938fdc4b65831893c6c96