Revert 284489 "Have media content and chrome browser tests load ..."
This broke the linux gn bot:

http://build.chromium.org/p/chromium.linux/builders/Linux%20GN%20%28dbg%29/builds/9676/steps/compile/logs/stdio

[824/4367 | 164.256] CXX
obj/media/video/capture/media_unittests.fake_video_capture_device_unittest.o
FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang++
-Wl,--fatal-warnings -m64 -fPIC -Wl,-z,noexecstack -Wl,-z,now
-Wl,-z,relro -B../../third_party/binutils/Linux_x64/Release/bin
-Wl,--icf=none -pthread -Wl,-rpath=\\\$ORIGIN/lib/
-Wl,-rpath-link=lib/ -o ffmpeg_unittests -Wl,--start-group
@ffmpeg_unittests.rsp  -Wl,--end-group  -ldl -lasound -lX11
-lXcomposite -lXcursor -lXdamage -lXext -lXfixes -lXi -lXrender -lXss
-lXtst -lgmodule-2.0 -lgobject-2.0 -lgthread-2.0 -lrt -lglib-2.0
-lnss3 -lnssutil3 -lsmime3 -lplds4 -lplc4 -lnspr4 -lfontconfig
-lfreetype -lpangocairo-1.0 -lpango-1.0 -lcairo 
obj/media/base/media_test_support.test_data_util.o:../../media/base/test_data_util.cc:function
media::StartMediaHttpTestServer():error: undefined reference to
'net::BaseTestServer::kLocalhost'
obj/media/base/media_test_support.test_data_util.o:../../media/base/test_data_util.cc:function
media::StartMediaHttpTestServer():error: undefined reference to
'net::LocalTestServer::LocalTestServer(net::BaseTestServer::Type,
std::string const&, base::FilePath const&)'
obj/media/base/media_test_support.test_data_util.o:../../media/base/test_data_util.cc:function
media::StartMediaHttpTestServer():error: undefined reference to
'net::LocalTestServer::Start()'
clang:error: linker command failed with exit code 1 (use -v to see
invocation)
...

> Have media content and chrome browser tests load data from media/test/data
> 
> Update remaining encrypted media browser tests to use new player app.
> 
> (This is identical to r282795 which got reverted, i.e. revert of revert).
> 
> The fix was submitted separately in r283757
> 
> BUG=379314
> 
> Review URL: https://codereview.chromium.org/398823004

TBR=shadi@chromium.org

Review URL: https://codereview.chromium.org/405803007

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@284495 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: d823551fe1c83a6647df2a92eec37172e112778b