Enable test LayerTreeHostTestBreakSwapPromise with verbose logging information
The log of the flaky LayerTreeHostTestBreakSwapPromise test shows that

[ RUN      ] LayerTreeHostTestBreakSwapPromise.RunMultiThread_DelegatingRenderer_ImplSidePaint
c:\b\build\slave\win_x64_builder\build\src\cc\trees\layer_tree_host_unittest.cc(4500): error: Value of: swap_promise_result_[2].did_not_swap_called
Actual: false
Expected: true
c:\b\build\slave\win_x64_builder\build\src\cc\trees\layer_tree_host_unittest.cc(4501): error: Value of: swap_promise_result_[2].reason
Actual: 0
Expected: SwapPromise::SWAP_FAILS
Which is: 1
[  FAILED  ] LayerTreeHostTestBreakSwapPromise.RunMultiThread_DelegatingRenderer_ImplSidePaint (3 ms)

We have a EXPECT_TRUE on the SwapPromise's dtor to be called which passes.
It means we destroyed the SwapPromise without ever breaking them first
(no DidNotSwap ever called). I checked all the code path where we destroy
SwapPromise and we always break them first. So I can't figure out why it
is the case. I am adding some logging information and turn this test back
on, hopefully next time it fails on the bot I can use the extra logging
information to debug.

BUG=393995

Review URL: https://codereview.chromium.org/477443002

Cr-Commit-Position: refs/heads/master@{#289679}
git-svn-id: svn://svn.chromium.org/chrome/trunk/src@289679 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: aa5d90ef6c87eb7a94ae343bb78e5f9d4ad40787