Revert 97557 - [chromedriver] Add chrome.detach option for configuring Chrome not to quit when its automation client disconnects. chrome.detach is currently implemented by using a NamedProxyLauncher. We also add a new switch that accomplishes the same purpose. Also, modify pre-post command execution steps in two ways: 1) wait for loads post execution, in case pyauto issues a non-webdriver command which expects the load to be finished 2) only  return a frame checking error if no alert is present
Reverting because of chromedriver_tests failure on windows.
http://build.chromium.org/p/chromium.pyauto/builders/Win%20XP/builds/9846/steps/chromedriver_tests/logs/stdio

ERROR: chromedriver_tests.DetachProcessTest.testDetachProcess: "None"
----------------------------------------------------------------------
Traceback (most recent call last):
    File
    "E:\b\build\slave\Win_XP\build\src\chrome\test\webdriver\test\chromedriver_tests.py",
    line 357, in testDetachProcess
        os.kill(pid, 0)  # Would throw if process no longer exists
    AttributeError: 'module' object has no attribute 'kill'

Feel free to recommit after fix (no review necessary)


BUG=87676,93438
TEST=none


Review URL: http://codereview.chromium.org/7648053

TBR=kkania@chromium.org
Review URL: http://codereview.chromium.org/7696022

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@97611 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: d5892a3904180a5a0db4d01586e08af2e5c480e0