dbus: don't add attributes in extern template class specialization
This previous CL added attributes to some template specializations:
https://codereview.chromium.org/408143012

This breaks gcc 4.8, which gives the following warning:
  ../../dbus/property.h:412:62: error: type attributes ignored after type is already defined [-Werror=attributes]

Since the template class already has the attribute, I suspect that the
additional attribute specifications are redundant.  ie I think we can
remove them.

Review URL: https://codereview.chromium.org/423233003

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@286567 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: b24773a4a86203823ae487f8281baa82ac907c47