Revert 206486 "Implement ChannelIDVerifier using NSS."
It breaks the ChromiumOS (amd64) build:
net/quic/crypto/channel_id_nss.cc: In static member function 'static bool net::ChannelIDVerifier::VerifyRaw(base::StringPiece, base::StringPiece, base::StringPiece, bool)':
net/quic/crypto/channel_id_nss.cc:55:20: error: narrowing conversion of 'signature.base::BasicStringPiece<std::basic_string<char> >::<anonymous>.base::internal::StringPieceDetail<STRING_TYPE>::size<std::basic_string<char> >()' from 'base::internal::StringPieceDetail<std::basic_string<char> >::size_type {aka long unsigned int}' to 'unsigned int' inside { } is ill-formed in C++11 [-Werror=narrowing]

> Implement ChannelIDVerifier using NSS.
> 
> Add known answer tests for ChannelIDVerifier. This requires adding a
> ChannelIDVerifier::VerifyRaw method that can verify a standard signature
> (as opposed to a ChannelID signature) because I only have test vectors
> for standard ECDSA signatures.
> 
> Disable the QuicCryptoServerStreamTest.ChannelID test.
> 
> R=agl@chromium.org,rtenneti@chromium.org
> BUG=none
> TEST=net_unittests --gtest_filter=ChannelIDTest.VerifyKnownAnswers
> 
> Review URL: https://chromiumcodereview.appspot.com/16638016

TBR=wtc@chromium.org

Review URL: https://codereview.chromium.org/17101004

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@206495 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 4a02b5d199e59d453a7ee573541aa6beab00b28d