Revert "Enable stack tool and ASan symbolization of logcat on Android bots."
This reverts commit aa3a0130e45f6484834432c9eb4a75f9e6ad81ee [formerly dc6d7c9d8d8bd5d29dd7a4fc681bb8c2a0bc3297].

Sorry, we can not commit this without the accompanying downstream change, because without that there are two --disable-stack-tool option strings (one in the downstream script and the newly added one here).

This causes the following error on the clank tot bot:
optparse.OptionConflictError: option --disable-stack-tool: conflicting option string(s): --disable-stack-tool

Link: https://chromegw.corp.google.com/i/clank.tot/builders/instrumentation-yakju-clankium-tot/builds/22826/steps/compile/logs/stdio

Reverting because this is keeping clank from picking up changes, and I'm not sure how to do a quick fix right now. Removing the option from clank requires the public script to have it, which requires clank to roll. Slightly tricky and I don't have the time to do it today.

TBR=craigdh@chromium.org,frankf@chromium.org,navabi@chromium.org,eugenis@chromium.org
NOTRY=true
BUG=325685

Review URL: https://codereview.chromium.org/154553003

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@248830 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: f6d2cba2529f2e4d828bd0e516eec7ab8169fdd6