Revert 110811 - Fix testAboutAppCacheTab by replacing External 500 error URL to working URL.
I'm reverting because this test is consistently failing on all bots. Remember
that it's the committer's responsibility to ensure that his change lands
safely.

======================================================================
FAIL: special_tabs.SpecialTabsTest.testAboutAppCacheTab: "Test App Cache tab to confirm about page populates caches."
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/data/b/build/slave/Linux__deb_/build/src/chrome/test/functional/special_tabs.py", line 317, in testAboutAppCacheTab
    self._VerifyAppCacheInternals()
  File "/mnt/data/b/build/slave/Linux__deb_/build/src/chrome/test/functional/special_tabs.py", line 207, in _VerifyAppCacheInternals
    [])
  File "/mnt/data/b/build/slave/Linux__deb_/build/src/chrome/test/functional/test_utils.py", line 232, in StringContentCheck
    msg='"%s" missing from content.' % s)
AssertionError: "Manifest" missing from content.

BUG=102517
TEST=none
Review URL: http://codereview.chromium.org/8533018

TBR=dyu@chromium.org
Review URL: http://codereview.chromium.org/8473011

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@110855 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 3e6743f1653f2ce96bde0d6e918175963efe01ee