Revert of Make LogMessage() handle strings with null bytes (https://codereview.chromium.org/198103008/)
Reason for revert:
Looks like this broke the Chromium OS builder.

hrome-35.0.1892.0_alpha-r1: FAILED: armv7a-cros-linux-gnueabi-g++ -B/usr/x86_64-pc-linux-gnu/armv7a-cros-linux-gnueabi/binutils-bin/2.22-gold -MMD -MF obj/base/base.logging.o.d -DV8_DEPRECATION_WARNINGS -DBLINK_SCALE_FILTERS_AT_RECORD_TIME -D_FILE_OFFSET_BITS=64 -DCHROMIUM_BUILD -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_CAIRO=1 -DUSE_CRAS=1 -DUSE_GLIB=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_X11=1 -DOS_CHROMEOS=1 -DUSE_XI2_MT=2 -DIMAGE_LOADER_EXTENSION=1 -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_INPUT_SPEECH -DENABLE_NOTIFICATIONS -DENABLE_HIDPI=1 -DENABLE_NEW_GAMEPAD_API=1 -DUSE_UDEV -DENABLE_EGLIMAGE=1 -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_AUTOMATION=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DENABLE_FULL_PRINTING=1 -DENABLE_PRINTING=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_MANAGED_USERS=1 -DENABLE_MDNS=1 -DUSE_SYMBOLIZE -DUSE_NSS=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DBASE_IMPLEMENTATION -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -D_FORTIFY_SOURCE=2 -I../../../../../../../home/chrome-bot/chrome_root/src -Werror -pthread -fno-exceptions -fno-strict-aliasing -Wall -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wno-unused-local-typedefs -pthread -I/build/daisy/usr/include/glib-2.0 -I/build/daisy/usr/lib/glib-2.0/include -march=armv7-a -mfpu=neon -mfloat-abi=hard -mthumb --sysroot=/build/daisy/ -O2 -fno-ident -fdata-sections -ffunction-sections -funwind-tables -g -pipe -march=armv7-a -mtune=cortex-a15 -mfpu=neon -mfloat-abi=hard -D__google_stl_debug_vector=1 -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -Wsign-compare -Wno-abi  -c ../../../../../../../home/chrome-bot/chrome_root/src/base/logging.cc -o obj/base/base.logging.o
chromeos-chrome-35.0.1892.0_alpha-r1: ../../../../../../../home/chrome-bot/chrome_root/src/base/logging.cc: In destructor 'logging::LogMessage::~LogMessage()':
chromeos-chrome-35.0.1892.0_alpha-r1: ../../../../../../../home/chrome-bot/chrome_root/src/base/logging.cc:600:62: error: ignoring return value of 'size_t fwrite(const void*, size_t, size_t, FILE*)', declared with attribute warn_unused_result [-Werror=unused-result]
chromeos-chrome-35.0.1892.0_alpha-r1:      fwrite(str_newline.data(), str_newline.size(), 1, stderr);
chromeos-chrome-35.0.1892.0_alpha-r1:                                                               ^
chromeos-chrome-35.0.1892.0_alpha-r1: ../../../../../../../home/chrome-bot/chrome_root/src/base/logging.cc:606:62: error: ignoring return value of 'size_t fwrite(const void*, size_t, size_t, FILE*)', declared with attribute warn_unused_result [-Werror=unused-result]
chromeos-chrome-35.0.1892.0_alpha-r1:      fwrite(str_newline.data(), str_newline.size(), 1, stderr);
chromeos-chrome-35.0.1892.0_alpha-r1:                                                               ^
chromeos-chrome-35.0.1892.0_alpha-r1: ../../../../../../../home/chrome-bot/chrome_root/src/base/logging.cc:631:66: error: ignoring return value of 'size_t fwrite(const void*, size_t, size_t, FILE*)', declared with attribute warn_unused_result [-Werror=unused-result]
chromeos-chrome-35.0.1892.0_alpha-r1:        fwrite(str_newline.data(), str_newline.size(), 1, log_file);
chromeos-chrome-35.0.1892.0_alpha-r1:                                                                   ^
chromeos-chrome-35.0.1892.0_alpha-r1: cc1plus: all warnings being treated as errors
chromeos-chrome-35.0.1892.0_alpha-r1: ninja: build stopped: subcommand failed.


http://build.chromium.org/p/chromium.chromiumos/builders/ChromiumOS%20%28daisy%29/builds/17147


Original issue's description:
> Make LogMessage() handle strings with null bytes
> 
> 'LOG(...) << std::string("a\0a", 3);' would cause the line to be
> truncated, and no newline output.
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=257093

TBR=thakis@chromium.org,brettw@chromium.org,darin@chromium.org,joaoe@opera.com
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/196133015

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@257095 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 9ba6fb19849e4b6f840e2b8893c5ce5d35c322ad